### ISSUE TITLE
Blacklist not available outside release?

### ISSUE THREAD

**Issue by Jeltje** [suhrig/arriba#1]
When I `git clone` this repo, I don't get the database subdirectory with the hg19 blacklist that's present in the release version `v0.11.0`.  The README mentions the blacklist but doesn't include it in the example run, and doesn't describe its use. This is a bit confusing.

**Comment by suhrig** [comment]
Hi Jeltje,

That is correct. It is not included in the repo and only available via the release. It's a relatively big binary file. Considering that I make minor updates to the list every once in a while and that I plan on releasing additional blacklists for hg38 and the mouse genome, this would quickly bloat the repository.

Common solutions to this include:
- Using Git LFS and the like. This, however, requires users to install LFS support without which the files will still be missing and therefore be equally confusing.
- Uploading the file to a separate location (such as the releases page).

If you are aware of a better solution, let me know. I'll make it more clear in the README. 

Regarding your second point, that the blacklist is not visible in the example command: I agree, I should make this a parameter to the script. I anyway have to, once multiple blacklists are available.

Regards,
Sebastian

**Comment by Jeltje** [comment]
I like the idea of using the releases page.
We usually use https://www.synapse.org/. It does require users to `pip install synapse` but after that the download is relatively straightforward - you could add a quick python script to the repo to automate it.

**Comment by suhrig** [comment]
With the new release, the README states more clearly, where to find the blacklist, and warns about cloning the repo. Moreover, the demo script `run_arriba.sh` now takes the blacklist as an argument, which should avoid the confusion about how to apply it. Thanks again for your feedback! I'm closing this issue.
