### ISSUE TITLE
-U not being passed to read subsampling stage

### ISSUE THREAD

**Issue by MattBashton** [suhrig/arriba#10]
Hi no matter what I set `-U` to _e_._g_. `1000` I will still receive the runtime message:

`Finding fusions and counting supporting reads (total=WARNING: Some fusions were subsampled, because they have more than 300 supporting reads 12129)`

It would appear that whilst the parameter is not being passed to the relevant subsampling routine.

**Comment by suhrig** [comment]
Thanks for pointing this out to me. It's a bug in parsing integer arguments that does not only affect -U. I will release a fix soon.

**Comment by suhrig** [comment]
Hi Matt,

The new release is out. It should fix this issue.

Regards,
Sebastian

**Comment by MattBashton** [comment]
Hey thanks good to know the feedback was useful, will test new release.

All the best,

Matt

**Comment by suhrig** [comment]
Closing this as solved. Thanks again for the hint!
