### ISSUE TITLE
sample names to draw_fusions.R

### ISSUE THREAD

**Issue by jemten** [suhrig/arriba#104]
Hi, 
Thanks for a very nice fusion caller and visualisation script!
Would it be possible to add the option to include a sample name on each plot from draw_fusion.R?
Cheers,
Anders

**Comment by suhrig** [comment]
Hi Anders,

Good suggestion! I will implement this and send you a notification when it's done. Probably this week. It should not be too complicated.

Regards,
Sebastian

**Comment by DarioS** [comment]
If you don't have many samples, [Inkscape](https://inkscape.org/) is a nice and free way to edit the plots, which are vector graphics.

**Comment by suhrig** [comment]
Hi Anders,

Here is a patched script that prints a sample name on every page: https://raw.githubusercontent.com/suhrig/arriba/develop/draw_fusions.R

You can pass the sample name via the parameter `--sampleName=...`. Make sure to wrap the name in quotes if it contains spaces.

Regards,
Sebastian

**Comment by jemten** [comment]
That was fast! 
Thanks a lot 
Anders
