### ISSUE TITLE
Output splits reads/discordant reads in BAM format

### ISSUE THREAD

**Issue by mjko1210** [suhrig/arriba#105]
Hi,

I'm wondering if theres is any way to extract splits reads/discordant reads (in bam format) related to final fusion candidate.
Ideally, I would like to highlight these reads from IGV viewer. 

Thanks,
MJ

**Comment by suhrig** [comment]
Hi MJ,

Here is a small Bash script that I hacked together just now: [extract_reads.txt](https://github.com/suhrig/arriba/files/6119225/extract_reads.txt)

You can change the file extension to `.sh` after download. GitHub only allows txt files to be uploaded. You also have to make it executable using `chmod a+x extract_reads.sh`. The script needs samtools >= 1.0, so make sure it is available in your `$PATH` environment variable. Once these steps are done, you can run it like this:

```
extract_reads.sh /path/to/fusions.tsv /path/to/Aligned.sortedByCoord.out.bam /path/to/output_prefix
```

For each fusion in the `fusions.tsv` file, the script fetches all reads from `Aligned.sortedByCoord.out.bam` that are listed as supporting reads for the given fusion. The reads are then written to a new BAM file named `/path/to/output_prefix_ID.bam`, where `ID` is the number of the fusion in Arriba's output file. This way you get all fusion-supporting reads in BAM separate files, which can be loaded into IGV. Is this what you are asking for?

There is no way to automatically highlight reads in IGV (like the `Select by name ...` function of IGV does). One can do a lot of stuff with auto-generated IGV session XML files, but highlighting reads by name is not even possible with that trick AFAIK.

Regards,
Sebastian

P.S. I have not done a lot of testing with the above script. Feel free to reach out to me again if you run into serious issues that you cannot solve yourself.

**Comment by mjko1210** [comment]
Thanks Sebastian for sharing your script.

`This way you get all fusion-supporting reads in BAM separate files, which can be loaded into IGV. Is this what you are asking for?` Yes. this is what I want.

I tried to run your script, however, I got following error:

extract_reads.sh: line 42: syntax error near unexpected token `('

Would you be able to fix this issues?

Thanks again!
MJ

**Comment by suhrig** [comment]
You are probably using an older version of Bash that does not understand process substitution. I updated the script in a way that does not make use of process substitution. Please download it again and check if that works.

**Comment by mjko1210** [comment]
Thanks for your quick reply! this works great :)

![igv_snapshot](https://user-images.githubusercontent.com/9116362/110753614-a3370b00-81fb-11eb-8b78-699ca8a4bad1.png)
I opened it from IGV viewer. Can I interpret two reads from gene1 and gene2 connected by a single line as split reads from the plot above?

**Comment by suhrig** [comment]
> Can I interpret two reads from gene1 and gene2 connected by a single line as split reads from the plot above?

In this particular case, yes. SLC45A3-ELK4 is a read-through fusion between neighboring genes. STAR usually represents such reads as a gapped alignment. In most situations, however, STAR produces a chimeric alignment, where distinct parts of a single read are aligned to multiple loci using clipped alignments. Here is an [IGV screenshot](https://arriba.readthedocs.io/en/latest/visualization/#inspection-of-events-using-igv) of what this looks like. The clipped segments map to the respective other breakpoint. You can highlight alignments that come from the same read by control-clicking an alignment, or by right-clicking anywhere and choosing `Select by name` and then typing the name of the read you want to be highlighted.

**Comment by suhrig** [comment]
I believe clipped segments are not shown by default in IGV. You have to enable them by navigating to View -> Preferences -> Alignments -> Show soft-clipped bases.

**Comment by mjko1210** [comment]
This is great! Thanks for sharing useful tips for fusion inspection from IGV.

**Comment by suhrig** [comment]
You're welcome1

**Comment by erprateek** [comment]
This should be a blog post! I believe a lot of people could use this knowledge. BTW I wrote something very similar to your script. I think your bam generation script deserves a place in your repository rather than just in an issue or could even exist as a flag that can turn on or off. Something like: --generate_fusion_bams [high/medium/low/all] that could generate the bams in a subdirectory inside the output path. Just a thought.

**Comment by suhrig** [comment]
Good suggestion. I could add a `scripts` folder in the repository with useful scripts for everyday tasks. I have a bunch and some of them are certainly worth sharing.

**Comment by suhrig** [comment]
There is now a script in the `develop` branch of the repository to do this:

https://github.com/suhrig/arriba/blob/develop/scripts/extract_fusion-supporting_alignments.sh

@mjko1210: The script I gave you originally has a bug that triggers, when the breakpoints are close to chromosome boundaries. I discovered it while running it on a few test samples. I suggest you update to the script in the repo.
