### ISSUE TITLE
Deterministic behavior

### ISSUE THREAD

**Issue by ju-mu** [suhrig/arriba#11]
Hi,

Thanks a lot for providing this fantastic, well documented tool.
Would it be possible to add a seed option to enable deterministic behavior of the subsampling routine (-U)?

Also, I have repeatedly run a few samples (v.0.12) with identical settings and most differences can possibly be explained by subsampling differences. There is however one difference in confidence of a fusion with only 2 supported reads I cannot explain:

Run 1:
`WDTC1 TBCEL    +/+         +/+         1:27561443          11:120957487     splice-site            splice-site            translocation                downstream      upstream            1              1              0              low         .               .               mismatches(1) GCGCCCCCCcTCCCGGGAGAGGGGCCGCCCCCCCCGGACGGACATGGGCTCCTGAAGTTGCGCCGCTGCCGGTCGGGGGAAGAGACCTGACAG|GTATCATGAACTGATCACTAAATATGGGAAGTTGGAGCCTTTGGCAGAAGTGGACCTAAGACCCCAGAGCAGTGCAAAAGTAGAAGTCCACTTTAACGATCAGGTGGAAGAAATGAGCATTCGTCTGGACCAAACAGTGGCA                .`
Run 2:
`WDTC1 TBCEL    +/+         +/+         1:27561443          11:120957487     splice-site            splice-site            translocation                downstream      upstream            1              1              0              medium               .               .               mismatches(1) GCGCCCCCCcTCCCGGGAGAGGGGCCGCCCCCCCCGGACGGACATGGGCTCCTGAAGTTGCGCCGCTGCCGGTCGGGGGAAGAGACCTGACAG|GTATCATGAACTGATCACTAAATATGGGAAGTTGGAGCCTTTGGCAGAAGTGGACCTAAGACCCCAGAGCAGTGCAAAAGTAGAAGTCCACTTTAACGATCAGGTGGAAGAAATGAGCATTCGTCTGGACCAAACAGTGGCA                .
`

Why is the same breakpoint once assigned with low- and once with medium confidence?
Is there a way to achieve completely reproducible results?

Many thanks!

**Comment by suhrig** [comment]
A [new release](https://github.com/suhrig/arriba/releases) is out, which (hopefully) fixes the non-deterministic behavior. In my tests, the only differences I noticed between runs were differently sorted entries in the file containing discarded fusions. This file is not meant to be sorted anyway. I also noticed differences, when you compile on different platforms and (sometimes) when you run on different platforms, where the underlying libraries differ. I'd argue that this is beyond the scope of Arriba's responsibility. Provided you have a consistent setup, the output should now be deterministic. Feel free to give it a try.
