### ISSUE TITLE
ERROR: could not find sequence of contig '1'

### ISSUE THREAD

**Issue by deb0612** [suhrig/arriba#113]
Dear sir,
I tried to use command below:
bash run_arriba.sh /STAR_index_GRCh38viral_GENCODE28/ GENCODE28.gtf /database/protein_domains_hg38_GRCh38_v2.1.0.gff3 
 database/blacklist_hg38_GRCh38_v2.1.0.tsv.gz /database/known_fusions_hg38_GRCh38_v2.1.0.tsv.gz /database/cytobands_hg38_GRCh38_v2.1.0.tsv 8 RNA-007A-WCJ_H7LJWDRXX_R1.clean.fastq.gz RNA-007A-WCJ_H7LJWDRXX_R2.clean.fastq.gz
The error shows up

![image](https://user-images.githubusercontent.com/29038270/116222151-e1bf5f80-a780-11eb-9550-3976eb3988a4.png)

**Comment by suhrig** [comment]
Your arguments are not correct. The file `protein_domains_hg38_GRCh38_v2.1.0.gff` is in the wrong place. The assembly FastA file is missing. And the file `cytobands_hg38_GRCh38_v2.1.0.tsv` has nothing to do with the script `run_arriba.sh` and should not be passed as an argument. Please have a look at the [quickstart guide](https://arriba.readthedocs.io/en/latest/quickstart/) for how to use the script correctly.

The cytobands file is supposed to be used for the generation of plots as described in the manual section [Visualization](https://arriba.readthedocs.io/en/latest/visualization/#publication-quality-figures).

**Comment by deb0612** [comment]
you are right!
I change my command into:
bash run_arriba.sh ~/STAR_index_GRCh38viral_GENCODE28/ ~/GENCODE28.gtf ~/GRCh38viral.fa "/NGS_Storage/Debbie/biotools/arriba_v2.1.0/database/blacklist_hg38_GRCh38_v2.1.0.tsv.gz" "/NGS_Storage/Debbie/biotools/arriba_v2.1.0/database/known_fusions_hg38_GRCh38_v2.1.0.tsv.gz" "/NGS_Storage/Debbie/biotools/arriba_v2.1.0/database/protein_domains_hg38_GRCh38_v2.1.0.gff3" 8 RNA-007A-WCJ_H7LJWDRXX_R1.clean.fastq.gz RNA-007A-WCJ_H7LJWDRXX_R2.clean.fastq.gz
It works.
