### ISSUE TITLE
Missing files ERROR: file not found/readable

### ISSUE THREAD

**Issue by BoudSTER** [suhrig/arriba#121]
Hello, 

First of all, thank you very much for your algorithm of detection of fusion which seems to be very robust according to many publications :).

However, I have a problem when I launch the command I get an error
"""
singularity exec \
> -B /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/nextflow_arriba/output:/output \
> -B /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/nextflow_arriba/references:/references:ro \
> -B /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/data_ext/L18122543/modi/l18122543_S15_R1.fastq.gz:/read1.fastq.gz:ro \
> -B /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/data_ext/L18122543/modi/l18122543_S15_R2.fastq.gz:/read2.fastq.gz:ro \
> /mnt/isilon_data_nfs/BIO_INFO/REPOSITORIES/SLUB_SINGULARITY-3/arriba/2.1.0/ea69432e352896f8b4f6e358189bdd8e.simg \
> arriba.sh
+ STAR_INDEX_DIR=/references/STAR_index_GRCh37_RefSeq_hg19
+ ANNOTATION_GTF=/references/RefSeq_hg19.gtf
+ ASSEMBLY_FA=/references/GRCh37.fa
+ BLACKLIST_TSV='/references/blacklist_*.tsv.gz'
+ KNOWN_FUSIONS_TSV='/references/known_fusions_*.tsv.gz'
+ TAGS_TSV='/references/known_fusions_*.tsv.gz'
+ PROTEIN_DOMAINS_GFF3='/references/protein_domains_*.gff3'
+ THREADS=8
+ READ1=/read1.fastq.gz
+ READ2=/read2.fastq.gz
++ dirname /arriba_v2.1.0/run_arriba.sh
+ BASE_DIR=/arriba_v2.1.0
+ STAR --runThreadN 8 --genomeDir /references/STAR_index_GRCh37_RefSeq_hg19 --genomeLoad NoSharedMemory --readFilesIn /read1.fastq.gz /read2.fastq.gz --readFilesCommand zcat --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentMin 10 --chimOutType WithinBAM HardClip --chimJunctionOverhangMin 10 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50
+ tee Aligned.out.bam
+ /arriba_v2.1.0/arriba -x /dev/stdin -o fusions.tsv -O fusions.discarded.tsv -a /references/GRCh37.fa -g /references/RefSeq_hg19.gtf -b '/references/blacklist_*.tsv.gz' -k '/references/known_fusions_*.tsv.gz' -t '/references/known_fusions_*.tsv.gz' -p '/references/protein_domains_*.gff3'
[2021-06-01T15:17:37] Launching Arriba 2.1.0
ERROR: file not found/readable: /references/blacklist_*.tsv.gz
"""
I have the impression that the files: blacklist_*.tsv.gz ; known_fusions_*.tsv.gz ; known_fusions_*.tsv.gz ; protein_domains_*.gff3 are missing and I don't know where to get them.

According to the documentation these files are found in the "release tarballs of Arriba" but by clicking on the link I could not find them in the realease :/

Thank you in advance for your time,

BoudSTER.

**Comment by BoudSTER** [comment]
It's ok I clicked on the wrong link :) sorry

**Comment by suhrig** [comment]
If you run the script `download_references.sh` from within the singularity container (see [quickstart guide](https://arriba.readthedocs.io/en/latest/quickstart/#installation-using-singularity)). It puts all the files in the right place automatically.

Anyhow, you seem to have found a solution yourself. So I'm closing this issue for now. Let me know if you run into any other issues. I'm glad to help.
