### ISSUE TITLE
Problem with RAM Consumption 

### ISSUE THREAD

**Issue by Evan-SF** [suhrig/arriba#122]
Hello,
Thank you for this tool ! I'm encountering a problem with Arriba with some of my samples, the RAM consumption explodes and go beyond 128Gb. It's problematic because I can't run the tool on a bigger infrastructure at the moment. But after all, is it normal ? I don't encounter this kind of problem with Star-Fusion. it seems the samples where Arriba fails have around 90 millions reads , maybe because of this fact ? Is there an option to limit the RAM consumption anywhere, like during the alignement ? 

Here is the code I ran into my SnakeMake pipeline : 
`
STAR \
        --runThreadN {threads} \
        --genomeDir {input.index} \
        --genomeLoad NoSharedMemory \
        --readFilesIn {input.fwd} {input.rev} \
        --readFilesCommand zcat \
        --outStd BAM_Unsorted \
        --outSAMtype BAM Unsorted \
        --outSAMunmapped Within \
        --outBAMcompression 0 \
        --outFilterMultimapNmax 50 \
        --peOverlapNbasesMin 10 \
        --alignSplicedMateMapLminOverLmate 0.5 \
        --alignSJstitchMismatchNmax 5 -1 5 5 \
        --chimSegmentMin 10 \
        --chimOutType WithinBAM HardClip \
        --chimJunctionOverhangMin 10 \
        --chimScoreDropMax 30     \
        --chimScoreJunctionNonGTAG 0 \
        --chimScoreSeparation 1 \
        --chimSegmentReadGapMax 3 \
        --chimMultimapNmax 50 | arriba \
        -x /dev/stdin \
        -o {output.fusions_arriba} \
        -O {output.fusions_discarded} \
        -a {input.hg38viral_fa} \
        -g {input.gencode_28_gtf} \
        -b {input.blacklist_hg38_GRCh38} \
        -k {input.known_fusions_hg38_GRCh38} \
        -t {input.known_fusions_hg38_GRCh38} \
        -p {input.protein_domains_hg38_GRCh38}
        '''
`
The problem occurs at this step : 
[2021-06-03T09:22:24] Reading chimeric alignments from '/dev/stdin'

The job is killed by the HPC (Sun Grid Engine) because it exceeds the allocated RAM. 

Thank you in advance for your answer. Best regards,
Evan

**Comment by suhrig** [comment]
Hi Evan,

This is not normal. I have run Arriba on samples with a billion reads with much less memory. The memory consumption really depends on the number of chimeric alignments, not the number of total alignments. Can you please run only STAR (without Arriba) and paste the contents of `Log.final.out`? Probably, the percentage of chimeric reads is very high, which is indicative of a problem with the sample or with computational processing.

Also, which version of STAR are you using? All but the very recent versions of STAR had a memory leak which caused memory consumption to increase with every chimeric alignment. You should check how much memory is consumed by STAR and how much by Arriba.

Regards,
Sebastian

**Comment by suhrig** [comment]
Another thing you can do is to run STAR and Arriba sequentially, rather than in parallel. Runtimes will be a few minutes longer, but you gain an additional 30-40GB of RAM for Arriba, which would otherwise be occupied by the STAR index.

**Comment by suhrig** [comment]
Hi Evan, do you have any updates on this?

**Comment by Evan-SF** [comment]
> Hi Evan, do you have any updates on this?

Hi, sorry for didn't give news earlier about this issue. My Star version is 2.7.8.a. Which Star version will you advice me to see if the problem comes from here ?

I will run Star and Arriba sequentially rather than in parallel.  I have good hope it will works as I will save around 40gb of RAM. 

I will give you the result as soon as possible, sorry again for the delay.

**Comment by suhrig** [comment]
No worries, just checking if this is still an issue.

STAR 2.7.8a is fine. It does not have the memory leak anymore.

Anyhow, I could very well imagine that something is odd about the sample. The STAR log file would be helpful to confirm this or rule it out. More than 70GB of RAM consumption by Arriba with just 90 million reads is very unusual. A substantial number of reads would have to be chimeric.

**Comment by Evan-SF** [comment]
> No worries, just checking if this is still an issue.
> 
> STAR 2.7.8a is fine. It does not have the memory leak anymore.
> 
> Anyhow, I could very well imagine that something is odd about the sample. The STAR log file would be helpful to confirm this or rule it out. More than 70GB of RAM consumption by Arriba with just 90 million reads is very unusual. A substantial number of reads would have to be chimeric.

Hi, so I come back with some news, I ran Arriba on two differents systems to identify if the problems comes from the system or the samples : 

- HPC
- Workstation with WSL2 (works fine to test my pipelines before launch them on HPC)

The problem with RAM consumption appears on the twice but I got more control to identify whats wrong thanks to the Workstation. Here is some screenshots which attest Arriba was consuming lots of RAM (approximately 60Gb alone on this sample). 

- Arriba & Star simultaneously during the mapping
https://zupimages.net/up/21/28/yeb1.png

- Arriba alone once STAR finished the mapping
https://zupimages.net/up/21/28/xp4d.png

I check the logs of the mapping and I'm pretty sure the problem comes from my samples (approximately 8 samples on +90) which have a pretty bad mapping score for this one : 70% of chimerics reads and 20% reads mapped to the genome. 

                                `Started job on |       Jul 15 16:46:25
                             Started mapping on |       Jul 15 16:47:29
                                    Finished on |       Jul 15 17:09:14
       Mapping speed, Million of reads per hour |       311.62

                          Number of input reads |       112961192
                      Average input read length |       152
                                    UNIQUE READS:
                   Uniquely mapped reads number |       22991615
                        Uniquely mapped reads % |       20.35%
                          Average mapped length |       151.56
                       Number of splices: Total |       4576447
            Number of splices: Annotated (sjdb) |       4427914
                       Number of splices: GT/AG |       4504738
                       Number of splices: GC/AG |       34760
                       Number of splices: AT/AC |       3632
               Number of splices: Non-canonical |       33317
                      Mismatch rate per base, % |       0.42%
                         Deletion rate per base |       0.01%
                        Deletion average length |       1.03
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.51
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       2887613
             % of reads mapped to multiple loci |       2.56%
        Number of reads mapped to too many loci |       36615
             % of reads mapped to too many loci |       0.03%
                                  UNMAPPED READS:
    Number of reads unmapped: too many mismatches |       21324
       % of reads unmapped: too many mismatches |       0.02%
            Number of reads unmapped: too short |       85715473
                 % of reads unmapped: too short |       75.88%
                Number of reads unmapped: other |       106153
                     % of reads unmapped: other |       0.09%
                                  CHIMERIC READS:
                       Number of chimeric reads |       80825696
                            % of chimeric reads |       71.55%
`

As the number of chimeric reads is huge I supposed it's normal for Arriba to gets overloaded because it never appear normally. 

So, I check meticulously the "wrong samples" and found there was a problem during the sequencing of theses samples which has been confirmed by the sequencing platform. An option has been activated by error of the sequencer "reversecomplement = 1". If I understood well this option had the effect of reversing the reads in the fastq and replacing each nucleotide with its complement. After reversed the problem and correct the samples I ran Arriba again and finally good results ! 

Firstly the mapping is completely different with an amount of 1% chimeric reads which is more "normal" 

                                `Started job on |       Jul 16 11:56:07
                             Started mapping on |       Jul 16 11:57:16
                                    Finished on |       Jul 16 12:17:18
        Mapping speed, Million of reads per hour |       338.32

                          Number of input reads |       112961192
                      Average input read length |       152
                                    UNIQUE READS:
                   Uniquely mapped reads number |       98953732
                        Uniquely mapped reads % |       87.60%
                          Average mapped length |       151.51
                       Number of splices: Total |       20504127
            Number of splices: Annotated (sjdb) |       20085358
                       Number of splices: GT/AG |       20274730
                       Number of splices: GC/AG |       142687
                       Number of splices: AT/AC |       17110
               Number of splices: Non-canonical |       69600
                      Mismatch rate per base, % |       0.29%
                         Deletion rate per base |       0.01%
                        Deletion average length |       1.45
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.45
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       7856517
             % of reads mapped to multiple loci |       6.96%
        Number of reads mapped to too many loci |       13782
             % of reads mapped to too many loci |       0.01%
                                  UNMAPPED READS:
     Number of reads unmapped: too many mismatches |       20895
       % of reads unmapped: too many mismatches |       0.02%
            Number of reads unmapped: too short |       5438529
                 % of reads unmapped: too short |       4.81%
                Number of reads unmapped: other |       106189
                     % of reads unmapped: other |       0.09%
                                  CHIMERIC READS:
                       Number of chimeric reads |       1219179
                            % of chimeric reads |       1.08%
`

Arriba finally ran well and I didn't encounter a big RAM consumption.

I think we can close the issue :)

**Comment by suhrig** [comment]
Glad you figured it out! I suspected there was something wrong with the sample ...
