### ISSUE TITLE
What is the source for included protein_domain_hg38?

### ISSUE THREAD

**Issue by ahdee** [suhrig/arriba#125]
Thanks, awesome fusion caller! I would like to know what the source is for the database for the protein_domains_hg38_GRCh38_v2.1.0.gff3? Thanks!

**Comment by suhrig** [comment]
It contains Pfam protein domains.

**Comment by ahdee** [comment]
@suhrig thanks but do you also know which site it was download at? I went to the pfam site but it looks there are no gff3 files?

**Comment by suhrig** [comment]
The GFF3 file is not available for download anywhere other than in the Arriba release package. On the Pfam site you will find [this file](http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/database_files/pfamA.txt.gz). To get the GFF3 file, you need to map the protein coordinates to genomic coordinates. I used the Bioconductor package `ensembldb` for this purpose. This is how the file was generated.

**Comment by ahdee** [comment]
@suhrig great thank you, this is very helpful.
