### ISSUE TITLE
Font change in draw_fusion.R

### ISSUE THREAD

**Issue by been9312** [suhrig/arriba#126]
Hi.

I want to change the font to times new roman, but I don't know where to change it inside draw_fusion.R script. Can I know if I can change it through another R function or if there is a factor in the script?

**Comment by suhrig** [comment]
I have just added a new parameter to the script to specify the font. You can find the enhanced script in the `develop` branch, here: https://raw.githubusercontent.com/suhrig/arriba/develop/draw_fusions.R

If you run it with `--fontFamily=Times`, then the fonts should all be in Times New Roman.

**Comment by been9312** [comment]
Thank you
