### ISSUE TITLE
Failed to run ./download_references.sh

### ISSUE THREAD

**Issue by Chaosli98** [suhrig/arriba#128]
Hi,
when i run my_path/var/lib/arriba/download_references.sh GRCh37viral+GENCODE19, it gets error: 
Downloading assembly: ftp://ftp.ensembl.org/pub/grch37/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz

gzip: stdin: unexpected end of file
and the same error with other COMBINATIONS, then i check the download_references.sh line 66-73, but it seems no problem....

Best,
jinhu

**Comment by suhrig** [comment]
Hi,

What happens when you download the file manually using the following commands?

```
wget ftp://ftp.ensembl.org/pub/grch37/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz
gunzip Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz
```

Do you get a more informative error message?

Regards,
Sebastian

**Comment by Chaosli98** [comment]
I just solved this problem, which seems to be related to the node where I ran the command, thanks for your reply!
