### ISSUE TITLE
fusion filtering issue

### ISSUE THREAD

**Issue by been9312** [suhrig/arriba#129]
Hi

I want to check the CIC-DUX4 fusion through arriba, but the other regions with the same sequence of DUX4 have read and cannot be drawn.

Is there a way to filter?

the reference is hg38
read sequence: GCGGCAGGGGCAGATGCAAGGCATCCCGGCGCCCTCCCAGGCGCTCCAGGGGCCGGCGCCCTGGTCTTCACTCCCCTGCGGCCTGCTGCTGGATGAGCTCCTGGCGAGCCCGGAGTTTCTGCAGCAGGCGACTCCTGGCGGTTTGATGCGC
figure was shown
![image](https://user-images.githubusercontent.com/41985962/130923135-aa5203ab-32fa-430d-bfb5-4bef3a96b3a4.png)

**Comment by been9312** [comment]
Hi.

Thank you for the comments.
I think method 1 worked well. However, the figure only appears as a fusion with 3'UTR of DUX4 even though the fusion occurs in exon1 of DUX4, when checking the bam file.
![image](https://user-images.githubusercontent.com/41985962/131286316-3844ba4d-1a13-42b4-b693-6809d3cbb19f.png)

It shows the same in second way.

In particular, the sequence written in figure is only found on the exon1 CDS region in DUX4, but can you tell me which part of the tsv file I need to modify to breakpoint? When I modified column 6; breakpoint 2, column 8; site:CDS, column16;reading_frame:in_frame, it appeared that I couldn't draw from R to error.

**Comment by suhrig** [comment]
> when checking the bam file

What do you mean by this? When you inspect it using IGV?

> In particular, the sequence written in figure is only found on the exon1 CDS region in DUX4

When I search the genome for the given sequence using Blat, finds 10 hits on chromosome 4 - all with exactly the same mapping quality. Only two of them hit an exon (chr4:190174804 and chr4:190065673). The one shown in your figure is outside the given paralog of DUX4 and therefore rendered as a breakpoint in the UTR.

It is not clear from the NGS data from which of the 10 loci the reads really originate from. Arriba picks a random (well, not 100% random) location and reports it. If you grep for `CIC` and `DUX4` in the discarded fusions file, you should find the others as well. You can extract your favorite solution and pass it to `draw_fusions.R`.

> When I modified column 6; breakpoint 2, column 8; site:CDS, column16;reading_frame:in_frame, it appeared that I couldn't draw from R to error.

What you describe sounds to me like you did everything right. What was the error message?

**Comment by been9312** [comment]
> What do you mean by this? When you inspect it using IGV?

Yes. I checked the bam file using IGV

> What you describe sounds to me like you did everything right. What was the error message?

First, I changed column 2; DUX4, column 6; chr4:190174804, column8; CDS, column16;in_frame
then the error message occurred.
`exon coordinates of CIC not found`
Even though I never changed CIC information.
And the figure showed `exon coordinates of DUX4 not found in RefSeq_hg38.gtf`

Second, I checked the gtf file.
The site chr4:190174804 is not located in gene_id "DUX4" but, gene_id "DUX4_4"
I changed column 2; DUX4_4, column 6; chr4:190174804, column8; UTR, column16;out-of-frame
Then the error message was same.

I used hg38viral.fa and RefSeq_hg38.gtf which were downloaded by download_references.sh

Did I miss anything?

**Comment by suhrig** [comment]
> Even though I never changed CIC information.

This is a bug which I noticed and fixed just recently, I just haven't pushed the fix to GitHub yet. The error message on the command line mentions the wrong gene name. The error message in the PDF is correct. Sorry for the confusion. This bug is not the cause of your problem, though. It must be something else.

> Did I miss anything?

After playing with some of the data you mentioned, I think the problem is that column 22 `gene_id2` also needs to be adapted. As the breakpoint used to be intergenic, I assume its value is currently a dot `.`. You need to change it to the gene ID of DUX4, which should be `DUX4_4`.

**Comment by been9312** [comment]
Finally, I did it.
The column 26's transcript_id2 should also be changed.
Thank you.
