### ISSUE TITLE
breakpoint1 for fusion where site1=intergenic

### ISSUE THREAD

**Issue by ypradat** [suhrig/arriba#130]
Hello there!

I came across a specific case that I thought would not occur and is causing me some troubles. I am aggregating the values from`#gene1`, `gene2`, `breakpoint1` and `breakpoint2` to build a unique fusion identifier and the case below is causing me a duplicated.

| #gene1                      | gene2 | strand1(gene/fusion) | strand2(gene/fusion) | breakpoint1 | breakpoint2 | site1      | site2       | type        |
|-----------------------------|-------|----------------------|----------------------|-------------|-------------|------------|-------------|-------------|
| FAM184B(13419),DCAF16(5724) | LCORL | ./-                  | -/-                  | 4:17794931  | 4:17845901  | intergenic | splice-site | duplication |
| DCAF16                      | LCORL | -/-                  | -/-                  | 4:17794931  | 4:17845901  | intron     | splice-site | duplication |

In the case site1 is intergenic, I am, in a first approximation, considering it as if there was a fusion between each of the 2 closest genes (i.e FAM184B and DCAF16 here) and gene2 (i.e LCORL). However, if I do this I end up with 2 fusions with the identifier

DCAF16/LCORL/4:17794931/4:17845901

What is the meaning of breakpoint1 when site1="intergenic"? How come it is the same value as the more regular fusion DCAF16--LCORL on the 2nd line?

Thank you very much in advance,
Yoann

**Comment by suhrig** [comment]
Hi Yoann,

This can happen in situations where the breakpoint is intergenic (does not hit a gene directly), but the reads supporting the fusion are spliced in a way that some part of the reads overlaps a gene. The breakpoint is then annotated as both intergenic and genic.

I agree this style of annotation is not ideal and should be considered a bug. I was not aware of this, as it happens only rarely - in my test data less than 0.5% of the time. So thanks for pointing this out to me.

The fix may be complicated and I am currently on vacation, so it may take a few weeks until I can provide you with a patch. I will keep you updated.

Regards,
Sebastian

**Comment by ypradat** [comment]
Hi Sebastian,

Thank you for your quick answer. I'll wait for your patch then.

Best,
Yoann

**Comment by suhrig** [comment]
Hi Yoann,

In version 2.2.0 of Arriba, which has just been released, breakpoints in the vicinity of a gene (but not inside) are now correctly tagged as `intergenic`. You may still occasionally see the same breakpoint annotated twice (once with the gene name and once with the neighboring genes) for the reasons outlined above. Thanks again for taking the time to report this issue.

Regards,
Sebastian
