### ISSUE TITLE
Dynamic view of results with Shiny R

### ISSUE THREAD

**Issue by lavauxt** [suhrig/arriba#134]
Just a suggestion for improvement, do you think it can be possible to integrate a dynamic view of the results with a Shiny R application ?
Like [for exemple](https://shiny.rstudio.com/gallery/genome-browser.html), with some interactions : choose a sample results from a list, download graphs in svg format, make annotation interactive, you name it...

**Comment by senzhaocode** [comment]
> thks for those answers, the conversion to vcf will be a good addition.
> the pdf to svg conversion is also a good point, i should have think of it before asking my question
> for the interactive part indeed it's beyond the arriba project, i was thinking of a way to display the graphs in a shiny R interface for ex, but it can be a silly idea ;-) because of the delay to compute the graphs

Hello, 

I think this link (https://github.com/senzhaocode/FuSViz) maybe  interesting for you - a shiny app to show SVs interactively, by combining RNA-seq and DNA-seq data together.
