### ISSUE TITLE
Reference issue from download_reference.sh

### ISSUE THREAD

**Issue by been9312** [suhrig/arriba#137]
I downloaded the hg38viral+Refseq reference through the download_reference script and proceeded with the arriba script. I checked that all of the draw_fusion.R script worked without any problem, but when I try to check the bam file with IGV, an error occurs.

![image](https://user-images.githubusercontent.com/41985962/142802142-97f7d248-3812-43be-aabb-5d42ae729c99.png)

I tried downloading another hg38 in the script, but the same problem occurred. I would like to ask if there is a problem with the reference or if you know a solution.

**Comment by suhrig** [comment]
Sorry you are having trouble with the custom assembly. This error is my fault. According to the SAM format specification, the RefSeq viral genomes shipped with Arriba contain invalid characters in the contig names. I did not remove them thoroughly. Most tools do not care, but IGV is picky about it. I have already prepared a fixed collection of RefSeq viral genomes, which you can download here until release v2.2.0 of Arriba is out:

https://c.1und1.de/@854294030366802154/lhFFG9dJRGK3TR5Tx6__zg

In addition to having valid contig names, this collection contains some more viruses, which improves detection of rare viruses (e.g., rare HPV strains).

**Comment by been9312** [comment]
Oh it was just my mistake. I did not analyze the viral genome.
So I just changed the reference to hg38 instead of hg38viral and it was confirmed that it was working well.

Thanks for considering.
