### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by matq007** [suhrig/arriba#14]
Would it be possible to wrap the tool into conda package and upload it to bioconda? I am working on a [rnafusion](https://github.com/nf-core/rnafusion) pipeline which consists of multiple tools for fusion detection. It would be super nice to implement your tool to the stack 🎉

**Comment by suhrig** [comment]
Hi Martin,

After someone made me aware of your project yesterday, I was going to get in touch with you anyway to discuss the possibility/technical details of integrating Arriba into your pipeline. You found me faster. :-)

Sure, I can prepare a bioconda package. If it suits your time frame, I will distribute it with the next stable release of Arriba, which I plan to release in a few weeks. I'll keep you updated.

Arriba's workflow is very similar to that of STAR-Fusion. I imagine we can make use of a lot of copy-pasta, which should facilitate the integration.

Regards,
Sebastian

**Comment by matq007** [comment]
Hi Sebastian, that sounds perfect. I am working on few changes now anyway so just let me know when you are ready 👍. I would like to include the tool in version 1.2 which will be maybe in a month or 2. 
Look forward 🎉 

Martin

**Comment by suhrig** [comment]
I managed to port the current version of Arriba (1.0.1) to bioconda. You should now be able to install it.  Version 1.1.0 is coming soon.

Three executables are installed:
* `arriba` (the core executable)
* `run_arriba.sh` (a simplistic script to run Arriba starting with FastQ files)
* `draw_fusions.R` (an R script to generate figures from the fusion predictions)

In addition, database files (blacklists, protein domains, cytobands, ...) are installed to `$CONDA_PREFIX/var/lib/arriba/`. You can find more information about all of these in the manual. You can let the content of `run_arriba.sh` be a guide to you on how to call the tool and integrate it into your pipeline. Let me know, if you need help.

**Comment by matq007** [comment]
That sounds perfect. I will probably wait for the 1.1.0 version so I can finish the report in the meantime. I've decided to have a separate repository for the report tool together with a scoring function of the fusions. You can see it [here](https://github.com/matq007/fusion-report). Look forward to implement the tool to the stack 👍

**Comment by suhrig** [comment]
FYI: Version 1.1.0 is out, along with instructions on how to install it using Bioconda: https://arriba.readthedocs.io/en/latest/quickstart/#installation-using-bioconda

**Comment by xiucz** [comment]
/+ 1 good job.

**Comment by matq007** [comment]
Hey @xiucz. I am trying to install arriba with conda but I always get stuck on `Solving environment: ...working...`. Have you encountered similar issues?

**Comment by suhrig** [comment]
I just tried it with the most recent Miniconda and it worked right away. But I can confirm this issue in general with conda. I have seen this with a number of packages. *sigh*

One of these might help:

- explicitly specify the version of Arriba you want to install (`conda install ... arriba=1.1.0`)
- only use the required channels and skip all other activated channels (`conda install --override-channels -c conda-forge -c bioconda -c defaults arriba=1.1.0`)
- update conda to the latest version

**Comment by matq007** [comment]
Thanks, finally managed to install it. I had a wrong order of the channels.
