### ISSUE TITLE
Issue with drawing fusion with hg19?

### ISSUE THREAD

**Issue by ahdee** [suhrig/arriba#140]
Hi, so I ran arriba for both hg38 and hg19; on the hg38 it renders the fusion perfectly and I can see that the fusion is what I would expect for the domains and breakpoints.  However on hg19 is a different story, the image it gives does not match what the breakpoint should be at and moreover, the domains are not correct. I followed the same instructions and used what was provided in the package in arriba_v.2.1.0 my command for hg19 was, 

```
Rscript /arriba/draw_fusions.R \
--fusions=/arriba/SSt_arriba_hg19_fusion.tsv \
--alignments=/arriba/SStAligned.sortedByCoord.out.bam \
--output=fusions.pdf \
--annotation=/arriba/GENCODE19.gtf \
--cytobands=/arriba/cytobands_hg19_hs37d5_GRCh37_v2.1.0.tsv \
--proteinDomains=/arriba/protein_domains_hg19_hs37d5_GRCh37_v2.1.0.gff3
```

here is the comparison between hg38 and hg19.  I ran arriba speratelty one for hg38 and then again for hg19 and although the coordinates are correct the image is not. 

image compare, hg39 vs hg19 https://www.dropbox.com/s/gw8imrtf9zl3z0m/xNpldN4Mbd.png?dl=0
tsv arriba output shorten to one fusion: https://www.dropbox.com/s/fxoj24efk40odmn/SSt_arriba_hg19_fusion.tsv?dl=1

**Comment by suhrig** [comment]
Several things in your plots do not look right. Arcs and labels are missing in several places. Very strange. I have not seen this before.

![rendering_issues](https://user-images.githubusercontent.com/10560654/146638613-4da5a89e-b9ec-4199-83b5-0d152810b43a.png)

Your Arriba TSV file produces a correct plot when I run it with `draw_fusions.R` from Arriba version 2.1.0. Something must be different in your environment. You should check the following:

1. Did you modify the `draw_fusions.R` script or is it corrupted? Can you double-check you are using the script from version 2.1.0?
2. The coverage track in the figure for hg19 is almost empty for FLI1. This means that the gene is hardly expressed. In the figure for hg38, FLI1 is expressed. Are you sure you used the same data for realignment? Can you check in IGV whether the hg19 alignments look good for EWSR1 and FLI1? I should mention that the transcript which `draw_fusions.R` chooses to visualize depends on the coverage of exons. If you give it a sample that expresses strange exons of EWSR1/FLI1, then strange transcripts will be chosen for visualization. This may explain why it chooses the wrong transcript for EWSR1.
3. The Arriba TSV file you sent me contains strange transcript names. They end on `.X_Y`, where `X` and `Y` are numbers. The transcripts should just end on `.X`. Did you adapt the GENCODE GTF file? Maybe this causes problems.
4. The missing arcs and labels in your plots could indicate a problem with your R installation or incompatibility with certain package versions used by `draw_fusions.R`. Can you send me the output of `Rscript -e 'library(GenomicRanges); library(circlize); library (GenomicAlignments); sessionInfo()'`? This would help me reproduce your installation and do some tests with it.

**Comment by ahdee** [comment]
@suhrig thank you so much for looking into this; these are excellent points. Importantly I'm glad you were able to construct the plots correctly for the hg19 on your end. So that means its something weird with what I'm doing.  I will test and report back. thanks again.

**Comment by ahdee** [comment]
@suhrig thank you I finally figure it out. It was what you said, I traced it back to genecode I downloaded. For whatever reason their annotations has an underscore for each of the gene; I found it here on biostar, https://www.biostars.org/p/437927/
what I did was removed all the underscore and number following it.  And it finally works.  

also good catch on the arches, yes this was a modify script.  The thing is, your fusion rendering is superior to any other fusion draws out there and I wanted a generic function that can take any outputs from the various programs out there. This is was a hack version and I must have missed something. If you have the time, do you mind taking a look? if not I totally understand.  

thank you and happy holiday.

**Comment by suhrig** [comment]
Glad you solved it.

I can have a look at your modified script. Maybe I can find a fix quickly. I am quite sure the underlying bug is the same as the one for the missing chromosome labels. If you manage to figure out why chromosome labels are missing, then the arcs should appear, too.

**Comment by suhrig** [comment]
Do you still want to send me your script for me to take a look, or have all issues been resolved by now?

**Comment by ahdee** [comment]
@suhrig thank you so much, sorry this slip by. Only if you have time, please help me take a look. I basically I modify your script so that it can take only any of caller by making the input a bit generic. The addon function starts in line 814: draw_fusion 

the other thing I changed was to save the exonbuild if it has already been done: that is on line 165; I think those are the only major changes.  The way it works is that I would source the file during a markdown report. Then call the draw_fusion fucntion which then produces a png that I then pull from the markdown to display it.  However as you pointed it out I might had messed up somewhere and the archs are not showing up. 

https://www.dropbox.com/s/hic9nfrmkptd9zz/draw_arriba.R?dl=1

Thanks again.

**Comment by ahdee** [comment]
Hey @suhrig thanks again for you time. I think you might be be right. I will check again using what you said.

**Comment by ahdee** [comment]
@suhrig hi just wanted to thank you again. Your debug was spot on for the missing chr labels.  The missing arcs was a big detective hunt for me. I finally narrowe it down and found out that it was because of the missing type. In an effort to have it draw out generic fusions I had missed the "type"; I solved it by implementing your missing type code.  
```# this is to draw the arcs for circos
test$type <- ifelse(test$contig1 != test$contig2, "translocation", ifelse(test$direction1 == test$direction2, "inversion", ifelse((test$direction1 == "downstream") == (test$breakpoint1 < test$breakpoint2), "deletion", "duplication")))```

**Comment by suhrig** [comment]
I'm glad you could fix it!
