### ISSUE TITLE
draw_fusions.R: Is it possible to visualize two positionally close fusions on a single figure?

### ISSUE THREAD

**Issue by mkazanov** [suhrig/arriba#145]
Hi,

Is it possible to visualize two positionally close fusions on a single figure using draw_fusions.R script?
I mean if we have fusions "gene1 + gene2" and "gene2 + gene3", and the part of the gene2 participating in these fusions
is sufficiently short.

Thanks

**Comment by suhrig** [comment]
This is not possible, sorry. The script is built to visualize only two genes at a time. You will need to merge the figures manually using image editing software. Make sure to use the parameter `--fixedScale=...`, such that all transcripts are on the same scale. You can find more details about this parameter in the manual, here: https://arriba.readthedocs.io/en/latest/command-line-options/#draw_fusionsr
