### ISSUE TITLE
Results from the SMC-RNA Challenge

### ISSUE THREAD

**Issue by raghavee** [suhrig/arriba#15]
Hi, 
I have read in your home page that as of the 4th round of the SMC-RNA challenge, Arriba has topped the leader board. Can you please share the results from that competition ? This will help me not to duplicate efforts in bench marking this tool against others. 

Thanks, 
RV

**Comment by suhrig** [comment]
Hi,

You can find the results of round 4 here (search for `uhrigs`): https://www.synapse.org/#!Synapse:syn2813589/wiki/423306

BTW, Arriba also won the fifth and final round (I just haven't updated the README yet), to be found here: https://www.synapse.org/#!Synapse:syn2813589/wiki/588511

The second link requires a (free) Synapse account, but give you more details (F1 score, true positive calls, total calls). I am not sure, why the organizers chose to hide the final results behind a login screen. I can ask them, if they want to open it up to the public. Anyone can create a Synapse account anyway ...

Regards,
Sebastian

**Comment by suhrig** [comment]
Have you found all the information you were looking for?

I got a response from the organizers why the results of the final round are hidden behind a login screen. It is for purely technical reasons. The table is auto-generated using the Synapse API, which apparently triggers the login screen.

**Comment by suhrig** [comment]
Hi raghavee, I'm closing this issue. Please reopen if you still need more info.
