### ISSUE TITLE
Draw_fusions.R - how to adjust the height of the coverage track?

### ISSUE THREAD

**Issue by nhjk-23** [suhrig/arriba#155]
Hi Sebastian,

Thank you for providing us with an amazing tool! 

I was wondering it it's possible to adjust the height (or scaling) of the coverage track? As you can see in the attached figure, because the coverage in the first gene is a lot higher than the second gene, the plot of the second gene looks like there's hardly any reads. Is it possible to adjust this - or in a sense have a different coverage scale between these two genes so that we can see peaks in the second gene?

Thanks!

[Coverage](https://user-images.githubusercontent.com/19342224/168191467-570a4157-1705-437a-8f31-a40a8c4fd4e0.png)

**Comment by suhrig** [comment]
Hi @nhjk-23,

Thanks for this useful suggestion. I have enhanced the script `draw_fusions.R` to give the user more control over the coverage range that should be drawn for gene1 and gene2:

- `--coverageRange=0`: automatically scale **both** coverage plots to the peak coverage of the fusion partner with the higher coverage (=current behavior)
- `--coverageRange=500`: crop **both** coverage plots to a maximum value of 500 or whatever value is specified (useful if you want to have the same scale across all fusions in the entire PDF and none of them exceeds the specified value)
- `--coverageRange=100,500`: crop the coverage plots **individually**, namely the left one to 100 and the right one to 500 (again, useful if you want to have the same scale throughout the entire PDF, but this time the scales for gene1 and gene2 should be different)
- `--coverageRange=0,0`: scale the coverage plots **individually**, namely the left one to the peak coverage of gene1 and the  right one to the peak coverage of gene2 (=what you are asking for)

You can download the new script here: https://raw.githubusercontent.com/suhrig/arriba/develop/draw_fusions.R

Please let me know if you run into any issues which I should fix before releasing the next version of Arriba.

Thanks,
Sebastian

**Comment by nhjk-23** [comment]
Hi @suhrig,

Thanks so much for this new script. I have tried the --coverageRange=0,0 option and it works well. However, I realised that this new modification is not compatible with the --squishIntrons=FALSE option? Do you think this can be fixed?

Thanks

![squishIntrons](https://user-images.githubusercontent.com/19342224/168701519-f499e280-3b39-4b34-a04d-2344bce8bf23.png)

**Comment by suhrig** [comment]
Well spotted, thanks! I forgot to remove some parentheses. Should be fixed now.

**Comment by nhjk-23** [comment]
Hi Sebastian,

Works perfectly! Amazing! Thank you so much for this. We'll be putting the plot in our manuscript, and of course we'll reference Arriba.

Thanks!
