### ISSUE TITLE
arriba vs starFusion/FusionInspector and protein frame call difference

### ISSUE THREAD

**Issue by alexander-e-f-smith** [suhrig/arriba#157]
Hi 
I have that arriba and starFusion/FusionInspector occasionally differ in opinion when it comes to calling the fusion protein frame when they have the same breakpoint coordinates  - see below for particular example which shows the 2 main fusion variants for 2 different SF/FI  workflows vs arriba workflow:
ID	                                 Fusion	          break_left	            break_right	        Frame
samp1-RNA_SF1pipe	ST7--MET	chr7:117020629:+	chr7:116699071:+	INFRAME
samp1-RNA_SF1pipe	ST7--MET	chr7:116953691:+	chr7:116699071:+	INFRAME
samp1-RNA_SF2Pipe	ST7--MET	chr7:117020629:+	chr7:116699071:+	INFRAME
samp1-RNA_SF2Pipe	ST7--MET	chr7:116953691:+	chr7:116699071:+	INFRAME
samp1-RNA_arribaPipe	ST7--MET	chr7:117020629	chr7:116699071	.
samp-RNA_arribaPipe	ST7--MET	chr7:116953691	chr7:116699071	in-frame

As you can see, SF/FI calls both fusion types "INFRAME" whereas for the same fusion breakpoint, Arriba only manages to call one in-frame, the other not called at all for frame. Is this a common occurrence and what could explain this? Thanks for your help again in this matter.

Best
A

**Comment by suhrig** [comment]
Hi Alex,

Can you send me the full output lines from Arriba, please? I have a suspicion as to where the discrepancy comes from, but need the additional info to confirm.

Thanks,
Sebastian

**Comment by alexander-e-f-smith** [comment]
Much appreciated, thank you!
A
