### ISSUE TITLE
Difference in non-template bases in fusions.tsv versus fusions.pdf

### ISSUE THREAD

**Issue by kvaldez** [suhrig/arriba#161]
Hi Sebastian,

Thanks again for this excellent tool, and for the continued updates to improve the functionality.  We have come across a difference between non-template bases in our fusion transcript when comparing the tsv (tctt) and pdf (tcctt) files.  Is this a potential bug, or is there an alternate explanation for the extra 'c'?

Please see the attached files for reference.

Thanks,
Kristin
[CP08794_T1R_T_HG3LHDRX2.ITD.csv](https://github.com/suhrig/arriba/files/8902791/CP08794_T1R_T_HG3LHDRX2.ITD.csv)
[CP08794_T1R_T_HG3LHDRX2.ITD.pdf](https://github.com/suhrig/arriba/files/8902792/CP08794_T1R_T_HG3LHDRX2.ITD.pdf)

**Comment by suhrig** [comment]
Hi Kristin,

Yep, that's a bug. Thanks a lot for reporting! Here is the fix:

https://raw.githubusercontent.com/suhrig/arriba/develop/draw_fusions.R

Regards,
Sebastian
