### ISSUE TITLE
Can this software get the sequence of the fusion gene?

### ISSUE THREAD

**Issue by wiltbb** [suhrig/arriba#166]
By fusion.tsv,I got  fusion_transcript.But there's no sequence for the fusion gene,can I get the sequence of the fusion gene?

**Comment by suhrig** [comment]
Which version of Arriba are you using? In versions < 2.x you had to enable the option `-T` for the fusion transcript to be computed. In versions >= 2.x, this feature is enabled by default and need no longer be toggled. In some situations, it can still happen, that the transcript sequence is empty (`.`), namely, when the computation was unsuccessful. But this should affect only a minority of the fusion calls.

**Comment by suhrig** [comment]
`fusion_transcript` contains the sequence of the fused genes. It only contains the parts of the genes that are retained in the fusion, e.g., if exons 1-3 of gene1 are fused to exons 12-18 of gene2, then the column only contains the sequence of these exons. It also only contains the transcribed regions, i.e., usually only the exons. And be default, Arriba only reports the sequence of the parts that are covered by fusion supporting reads. If you want the full fusion sequence you need to add the parameter `-I`, which instructs Arriba to take information from the reference genome when the fusion transcript cannot be assembled completely (from start to end) using just the fusion-supporting reads. Does this answer your question? If not, can you give an example of what info you are looking for?

**Comment by wiltbb** [comment]
Now I added the parameter `-I`,I found much longer `fusion_transcript`,I think I got my answer.I need the full fusion sequence to do a polymorphism analysis.
