### ISSUE TITLE
How to get the exon number from output?

### ISSUE THREAD

**Issue by bbgbb** [suhrig/arriba#168]
Hi,

I want to check the exon number of the fusion gene but i don't find how to...
What command should I use to get the exon number?

Thanks!

**Comment by suhrig** [comment]
Hi,

The exon numbers are shown in the PDF file generated by `draw_fusions.R`. Or do you need them in a machine-readable format?

Regards,
Sebastian

**Comment by bbgbb** [comment]
Hi @suhrig ,

Thanks for your reply! I saw the exon numbers can be shown in PDF file. And I wonder whether them can be in format like dataframe (csv or txt)?

Thanks

**Comment by suhrig** [comment]
Here is a script which appends two columns with the exon numbers to Arriba's output files: [annotate_exon_numbers.sh.zip](https://github.com/suhrig/arriba/files/9667448/annotate_exon_numbers.sh.zip). Run it without arguments to learn about the usage.

Let me know if you have trouble using it. I tested it on a few files and it seemed to work fine.

**Comment by bbgbb** [comment]
Hi Sebastian @suhrig ,

The script is super helpful! Thanks a lot for your help! Hope you have a nice day.=)

Thanks again.
