### ISSUE TITLE
PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions

### ISSUE THREAD

**Issue by deb0612** [suhrig/arriba#172]
Dear sir,
I use  command : bash "/biotools/arriba_v2.3.0/run_arriba.sh" "/biotools/arriba_v2.3.0/STAR_index_GRCh38_GENCODE38/" "/biotools/arriba_v2.3.0/GENCODE38.gtf" "/biotools/arriba_v2.3.0/GRCh38.fa" "/biotools/arriba_v2.3.0/database/blacklist_hg38_GRCh38_v2.3.0.tsv.gz" "/biotools/arriba_v2.3.0/database/known_fusions_hg38_GRCh38_v2.3.0.tsv.gz" "/biotools/arriba_v2.3.0/database/protein_domains_hg38_GRCh38_v2.3.0.gff3" 
8 
rePB223_S101_L002_R1_001.fastq.gz rePB223_S101_L002_R2_001.fastq.gz
and show the error message 

EXITING because of fatal PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions
SOLUTION: re-run with --chimOutType Junctions

![image](https://user-images.githubusercontent.com/29038270/204196157-d9924cce-6108-42d8-a410-2f5ac5d3d0a3.png)

**Comment by suhrig** [comment]
You need to install a more recent version of STAR. I recommend the most recent version.

**Comment by deb0612** [comment]
Thanks, I tried to update my star to the latest version 2.7.10b, and other error occurred!
![image](https://user-images.githubusercontent.com/29038270/205307564-82a4d966-2ce5-41db-9d7e-0e30eee4c2d1.png)

**Comment by suhrig** [comment]
Apparently, the NAS storage on which you are running the script does not support FIFO files. STAR needs to create these files in order to run. Can you launch the script on a file system which supports FIFOs? For example, `/tmp` usually works.

**Comment by suhrig** [comment]
Did it work with `/tmp`?
