### ISSUE TITLE
Arriba's STAR parameters: is HardClip in "--chimOutType WithinBAM HardClip" required?

### ISSUE THREAD

**Issue by toddajohnson** [suhrig/arriba#173]
Hi Sebastian,

Is "HardClip" required for chimeric reads output in the STAR aligned bam file, or is it OK to use "SoftClip" in the --chimOutType?  I have been using STAR aligned bam files with softclipped reads in order to see the breakpoints in IGV, but I thought that I should check and make sure that nothing unexpected might be happening under the hood with respect to Arriba's fusion detection.

Thanks,
Todd

**Comment by suhrig** [comment]
Hi Todd,

It makes no difference whatsoever. You can use whatever you prefer.

Regards,
Sebastian

**Comment by toddajohnson** [comment]
Thank you for the clarification!
