### ISSUE TITLE
recommanded way to make custom blackfile

### ISSUE THREAD

**Issue by rLannes** [suhrig/arriba#174]
I am working on D.Melanogaster
I want to make a custom blaclist.
I have three control biological replicate.

Do you have a recommended way to build a blaclist from those control?
I did not find it, in the documentation...

Best

**Comment by suhrig** [comment]
Just run Arriba on all control samples that you have. Then, extract the breakpoint pairs (from the columns `breakpoint1` and `breakpoint2`) from both the main output file (specified by `-o`) and the discarded fusions output file (specified by `-O`) and store them in a tab-separated file. That's it. For example, your final output file might look like this:

```
chr1:7832947	chr4:3728734
chr22:4782312	chr6:12983794
... and so on
```

Optionally, you can manually fine-tune the blacklist with special keywords or gene names if you find that some genes give rise to artifacts that escape the blacklist. The format of the blacklist and the valid keywords are documented here: https://arriba.readthedocs.io/en/latest/input-files/#blacklist This is entirely optional, however. A blacklist based on observed breakpoint pairs will do a good job already.

Three samples is not a lot to build a blacklist. The more samples you have the better. The blacklists distributed with Arriba were build from hundreds to thousands of samples. They include all recurrent breakpoint pairs, i.e., breakpoints that were found in at least two samples. If you only have three samples, then it is probably best to also blacklist non-recurrent breakpoint pairs, i.e., breakpoints that are found in only one sample.
