### ISSUE TITLE
Invalid file when converting fusions to vcf

### ISSUE THREAD

**Issue by FelixMoelder** [suhrig/arriba#177]
First of all thank you for developing arriba!

While working with you tool I realized that the vcf created by applying the `convert_fusions_to_vcf.sh`-script appears to be invalid for post processing with bcftools.
While printing the content of the vcf-file with `bcftools view` generally works converting to a bcf-file does not as bcftools fails with the following output:
```
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::bcf_write] Unchecked error (1) at 1:4226451
[main_vcfview] Error: cannot write to (null)
```

The reason for failing seems to be simple as there is no `contig` defined in the vcf-header.
It would be nice if the script could be extended adding contig-fields to the header.

**Comment by suhrig** [comment]
Thank you for making me aware of this. I just pushed an enhanced version of the conversion script to the code repository. It adds contig IDs to the VCF header, which solves the error from bcftools in my tests. Feel free to try it out:

https://raw.githubusercontent.com/suhrig/arriba/develop/scripts/convert_fusions_to_vcf.sh
