### ISSUE TITLE
Does Arriba do reads downsampling by default?

### ISSUE THREAD

**Issue by liuxiii** [suhrig/arriba#178]
For the following RNA seq fusions, Arriba's read depth are all lower than Basespace's. Does it caused by Arriba do reads downsampling by default?

gene1 | gene2 | Basespace |   |   | Arriba |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | split | paired | total | split | paired | total
EWSR1 | FLI1 | 33 | 23 | 56 | 1 | 2 | 3
KANSL1 | KAT6B | 13 | 5 | 18 | 0 | 0 | 0
TFE3 | PHF1 | 11 | 4 | 15 | 0 | 0 | 0
EML1 | NTRK2 | 26 | 11 | 37 | 3 | 0 | 3
CD74 | ROS1 | 29 | 25 | 54 | 3 | 8 | 11
COL1A1 | PDGFB | 4 | 0 | 4 | 0 | 0 | 0
CCDC6 | RET | 8 | 7 | 15 | 0 | 3 | 3
EWSR1 | NR4A3 | 3 | 0 | 3 | 0 | 0 | 0
FUS | CREB3L2 | 11 | 7 | 18 | 1 | 2 | 3
igfbp5 | alk | 60 | 21 | 81 | 5 | 1 | 6
TFE3 | PRCC | 11 | 9 | 20 | 1 | 0 | 1
ROS1 |   | 26 | 29 | 55 | 7 | 6 | 13

</body></html></div>

Thank you,
Xin

**Comment by suhrig** [comment]
Hi Xin,

Yes, Arriba does perform downsampling by default, but only when it has collected a more than sufficient number of supporting reads (over 300 is the default threshold). In addition, some reads may be discarded by its filters. You can find them in the column `filters`. And lastly, some reads may be missed by the underlying algorithm (STAR). All of these factors contribute to the read counts being lower than those of BaseSpace. It's impossible to tell what's the reason from only the numbers you sent.

Your data looks like a benchmark sample. Is this correct? Could you share the FastQ files with me? I curious to find out which reads Arriba lost compared to BaseSpace. Maybe I can improve the filters.

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Xin,

Let me reiterate my offer: if you have the possibility to share the data, then I will gladly take a look at what is going wrong.

In the meantime, here is one check you can perform on your own and which is often the culprit for massive loss of fusion-supporting reads: Your library may have a small insert size, such that much of the read is actually adapter sequence. Take a look at the STAR log file. If the value of ` % of reads unmapped: too short` is high, then most likely this is the problem. In this case, you should trim your reads prior to alignment. There are some instructions in the manual: https://arriba.readthedocs.io/en/latest/current-limitations/#adapter-trimming

Secondly, if this is panel sequencing data, you should be aware that the default method that Arriba uses for duplicate detection may not be optimal. Check out this section from the manual for more details: https://arriba.readthedocs.io/en/latest/current-limitations/#targeted-sequencing

Regards,
Sebastian

**Comment by liuxiii** [comment]
Hi Sebastian,

Many thanks for your suggestions and I will have a look the insertion size and the duplication deletions.
I personally would like to share the data, but I am not sure whether this is allowed or not, as the data belong to NHS and I remembered all the data need to be within UK. I will ask my boss after she come back in the new year.

Best,
Xin
________________________________

**Comment by liuxiii** [comment]
Hi Sebastian,


For the 4 samples which has no reads for SV:

% of reads unmapped: too short | 4.20%

% of reads unmapped: too short | 4.21%

% of reads unmapped: too short | 7.73%

% of reads unmapped: too short | 4.98%

Do you think their "% of reads unmapped: too short" too high?

Yes, We are using Pan Cancer Panel, maybe we should use '-u', but none of our RNA samples use UMI. I am not sure whether using '-u' will enlarge false positive number.

Thanks,
Xin
________________________________

**Comment by suhrig** [comment]
I have seen worse than 4-8% of "unmapped: too short" reads. Still, I think it's a good idea to try out whether trimming your reads prior to alignment improves the results notably.

If you don't have UMIs, then using `-u` is not appropriate and could lead to false positives. Unless your library is designed in a way that amplifies predefined fusions using pairs of fixed primers. You should just try it out and see if the numbers from Arriba come close to those from BaseSpace. Maybe BaseSpace does not perform duplicate removal.

**Comment by suhrig** [comment]
Hi Xin,

Have you had any success with trimming? Do you still need help with this?

Regards,
Sebastian

**Comment by liuxiii** [comment]
No, the trimming not helpful, but we found out the root reason, which is the demplitplexing was done twice and the fqs was added up.

Thanks for all your suggestions, which widen our vision!

Best,
Xin
________________________________

**Comment by suhrig** [comment]
Glad to hear you figured it out!
