### ISSUE TITLE
no split reads or discordant mates found

### ISSUE THREAD

**Issue by kwanghoon821** [suhrig/arriba#180]
Hi, I'm trying to use Arriba.
I have generated BAM file with STAR based on the codes of Arriba's workflow (some adjustment have been done).

First, this is my STAR alignment code

```
STAR --genomeDir arriba_v2.3.0/STAR_index_GRCh37_GENCODE19 \
--genomeLoad NoSharedMemory \
--runThreadN 16 \
--readFilesCommand gunzip -c \
--readFilesIn RT_1.fastq.gz RT_2.fastq.gz \
--outFileNamePrefix RT_ \
--outSAMtype BAM SortedByCoordinate \
--outSAMattributes Standard \
--outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 \
--chimSegmentMin 10 --chimOutType WithinBAM HardClip --chimJunctionOverhangMin 10 --chimScoreDropMax 30 \
--chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50
```

As you can see, I used "--chimOutType WithinBAM HardClip".
So, I skipped the argument -c in arriba commend like below.

```
arriba_v2.3.0/arriba \
-x RT_Aligned.sortedByCoord.out.bam \
-o RT_fusions.tsv -O RT_fusions.discarded.tsv \
-g /arriba_v2.3.0/GENCODE19.gtf \
-a /arriba_v2.3.0/GRCh37.fa \
-b /arriba_v2.3.0/database/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz \
-k /arriba_v2.3.0/database/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz \
-p /arriba_v2.3.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
```

But error message showd up that I need to use the argument -c with 'Chimeric.out.sam'
ERROR: no split reads or discordant mates found (STAR must either be run with '--chimOutType WithinBAM' or the file 'Chimeric.out.sam' must be passed to Arriba via the argument -c)

Help me please,,,

**Comment by suhrig** [comment]
Hm, your code looks okay as far as I can tell. You are right in that you do not need the parameter `-c` if you use `--chimOutType WithinBAM` for alignment. I am not sure what could be the issue here. Does it work with the demo script `run_arriba.sh`? How many reads are in the FastQ files? Maybe the sample is very small and there really simply aren't any split reads or discordant mates. What does STAR report for `Number of chimeric reads` in the log file `Log.final.out`?

**Comment by kwanghoon821** [comment]
> Hm, your code looks okay as far as I can tell. You are right in that you do not need the parameter `-c` if you use `--chimOutType WithinBAM` for alignment. I am not sure what could be the issue here. Does it work with the demo script `run_arriba.sh`? How many reads are in the FastQ files? Maybe the sample is very small and there really simply aren't any split reads or discordant mates. What does STAR report for `Number of chimeric reads` in the log file `Log.final.out`?

I ran **run_arriba.sh** using my FastQ and the same error was occured.

These are what you requested.

Total read: 131,168,624
CHIMERIC READS:
Number of chimeric reads |	1399775
% of chimeric reads |	2.13%

I also ran with **--chimOutType SeparateSAMold** and the same error was occured.

Hmm,,,

STAR version: STAR-2.7.10b

**Comment by suhrig** [comment]
> Number of chimeric reads | 1399775

This should be enough. Does your script work with the FastQ files in the `test` folder? If it does, then it's a problem with the sample. If it doesn't, it's a problem with the script or reference files.

If it's a problem with the sample, can you share it with me? Alternatively, you can extract a few chimeric assignments from the BAM file using the following command:

```
samtools view Aligned.sortedByCoordinate.out.bam | grep SA:Z: | head
```

**Comment by kwanghoon821** [comment]
Hmm...

I have re-installed Arriba and downloaded the reference files(GRCh37 + GENCODE) again.
But still, even demo scripts didn't work.

`[2022-12-30T12:02:06] Reading chimeric alignments from '/dev/stdin' ERROR: no split reads or discordant mates found (STAR must either be run with '--chimOutType WithinBAM' or the file 'Chimeric.out.sam' must be passed to Arriba via the argument -c)`


This is my demo script.

```
path/to/run_arriba.sh \
path/to/GRCh37/STAR_index_GRCh37_GENCODE19 \
path/to/GRCh37/GENCODE19.gtf \
path/to/GRCh37/GRCh37.fa \
path/to/database/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz \
path/to/database/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz \
path/to/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3 \
8 \
read1.fastq.gz read2.fastq.gz

```


I think it's my problem, not arriba.
Is there any package I need other than STAR?

**Comment by suhrig** [comment]
It must be a problem with the sample, then. Have you tried running the small test sample from the `test` folder? Can you send me a few chimeric alignments from your problematic sample using the following command?

```
samtools view Aligned.sortedByCoordinate.out.bam | grep SA:Z: | head
```

I would like to double-check that the alignments are in the proper format.

> Is there any package I need other than STAR?

No. `run_arriba.sh` only needs STAR. It also makes use of samtools, but only after calling fusions with arriba, and this step is optional.

**Comment by kwanghoon821** [comment]
I'm terribly sorry.
I thought I was using STAR 2.7.10b STAR (cause I downloaded and compiled it), but my server's environment which is provided by my institution was using STAR 2.6......................

I made a docker environment, and re-setup packages and it worked.

So embarrassing...

Thank you for your passionate support.

**Comment by suhrig** [comment]
No worries. I'm just glad you were able to solve this mystery. Have a good start into the year!
