### ISSUE TITLE
Different gene fusions from the same alignments

### ISSUE THREAD

**Issue by Gaura** [suhrig/arriba#182]
Hi,

Thanks for developing arriba. I was experimenting with fastp to remove `polyX` tail from fastq. I generated 2 files, one with the `polyX(-x)`  removal flag and one without, let's call them *"trimX"* and *"noTrim"*, resp. Then exactly the same STAR and arriba commands were run on both the files  (as recommended on the [arriba website](https://arriba.readthedocs.io/en/latest/)). This structural variant was detected on the noTrim pipeline:
```
   #gene1 gene2 strand1(gene/fusion) strand2(gene/fusion)    breakpoint1    breakpoint2           site1           site2                               type
HSPH1 HSPH1                  -/-                  -/- chr13:31137368 chr13:31143923 CDS/splice-site CDS/splice-site duplication/non-canonical_splicing
   split_reads1 split_reads2 discordant_mates coverage1 coverage2 confidence reading_frame tags                retained_protein_domains
           2            0                0         4         6        low             .    . Hsp70_protein(100%)|Hsp70_protein(100%)
   closest_genomic_breakpoint1 closest_genomic_breakpoint2           gene_id1           gene_id2    transcript_id1    transcript_id2 direction1 direction2
                           .                           . ENSG00000120694.20 ENSG00000120694.20 ENST00000435381.5 ENST00000445273.6   upstream downstream
   filters                                                                                                     fusion_transcript peptide_sequence
       . ATTGATAAAAAGGAAGAAGATTTAGAAGACAAAAACAATTTTGGTGCTGAACCTCCACATCAGAATG|AAAAATGTCCAGCAAGACAACAGTGAAGCTGGAACACAGCCCCAGGTAC                .
                          read_identifiers
SRR12519533.2801581,SRR12519533.4914098
```

I checked the `Aligned.out.bam` STAR file for the alignment of the 2 reads: `SRR12519533.2801581` and `SRR12519533.4914098`. The alignments were exactly the same in both *noTrim* and *trimX* runs, but the fusion was not called by arriba in the *trimX* case. 
Here are the alignments from STAR. 
```
SRR12519533.2801581	16	chr13	31137368	255	49S52M	*	0	0	GTACCTGGGGCTGTGTTCCAGCTTCACTGTTGTCTTGCTGGACATTTTTCATTCTGATGTGGAGGTTCAGCACCAAAATTGTTTTTGTCTTCTAAATCTTC	F>GBGGDGGGDGGBGGGGGGGGGGGGG@0GGGF>GGGGGGGGGEGGGGCGGGGGGGGGGDBGGGGFDCGGBGGGGCGGGGBGGGGGGGDGGGGGGFA<333	NH:i:1	HI:i:1	AS:i:51	nM:i:0	NM:i:0	SA:Z:chr13,31143875,-,49M52H,255,0;
SRR12519533.2801581	2064	chr13	31143875	255	49M52H	*	0	0	GTACCTGGGGCTGTGTTCCAGCTTCACTGTTGTCTTGCTGGACATTTTT	F>GBGGDGGGDGGBGGGGGGGGGGGGG@0GGGF>GGGGGGGGGEGGGGC	NH:i:1	HI:i:1	AS:i:48	nM:i:0	NM:i:0	SA:Z:chr13,31137368,-,49S52M,255,0;
SRR12519533.4914098	2048	chr13	31143890	255	34M67H	*	0	0	TTCCAGCTTCACTGTTGTCTTGCTGGACATTTTT	BBBC011;1;E@D1=>@B1;B>CFGG0@@F@11F	NH:i:1	HI:i:1	AS:i:33	nM:i:0	NM:i:0	SA:Z:chr13,31137368,+,34S67M,255,0;
SRR12519533.4914098	0	chr13	31137368	255	34S67M	*	0	0	TTCCAGCTTCACTGTTGTCTTGCTGGACATTTTTCATTCTGATGTGGAGGTTCAGCACCAAAATTGTTTTTGTCTTCTAAATCTTCTTCCTTTTTATCAAT	BBBC011;1;E@D1=>@B1;B>CFGG0@@F@11FFEGGGGG=CF@1F>GD/E1E:ED>:FEG0FDF:F::0:CEGGGG@=@0EFG>FEEGCGGGG>:0=@F	NH:i:1	HI:i:1	AS:i:65	nM:i:0	NM:i:0	SA:Z:chr13,31143890,+,34M67H,255,0;
```

Can you tell me why could that be the case? In case you need any other info, please let me know.

**Comment by suhrig** [comment]
Hi,

When you trim reads, some alignments will be different (albeit not the ones belonging to the fusion in question). Arriba uses **all** chimeric alignments to estimate the background noise. Samples with a high fraction of chimeric alignments are processed with more stringent filters by Arriba, meaning that a fusion must have more read support for Arriba to make a call. The fusion in question was probably at the detection limit, and a slight change in Arriba's estimate of the background noise either causes the fusion to be called or not called. I hope this answers your question.

BTW, the fusion has low confidence. Those are fusion candidates at the detection limit or with otherwise dubious characteristics. As much as 90% of the low-confidence fusions can be false positives, so you should treat them with skepticism anyway.

Regards,
Sebastian

**Comment by Gaura** [comment]
Thanks for your reply, @suhrig! This is helpful. :)
