### ISSUE TITLE
On the classification of the results about the fusion_transcript

### ISSUE THREAD

**Issue by wiltbb** [suhrig/arriba#183]
I use the `-I` parameter to get the fusion_transcript in the result `.tsv` file,Could I combline all these `fusion_transcript` sequences as a reference genome file? Then I use my resequencing data,format as `.fastq.gz`,mapping to the reference genome file.If the sample in high mapping rate,it indicates that the fusion gene is the fusion gene before transcription,or indicates that these fusion gene are formed after transcription.

**Comment by suhrig** [comment]
> Could I combline all these fusion_transcript sequences as a reference genome file?

Yes. Just make sure you remove the special characters, leaving only bases ATCGatcg. And also beware that the full fusion transcript cannot always be assembled fully even when `-I` is used.

> If the sample in high mapping rate,it indicates that the fusion gene is the fusion gene before transcription,or indicates that these fusion gene are formed after transcription.

It is impossible to tell with certainty from RNA-Seq data whether a fusion is created before transcription (i.e., as a result of a genomic rearrangement) or after transcription (i.e., as an effect of splicing). Both fusions look alike in RNA-Seq data. You need whole-genome sequencing data to distinguish the two. So I don't think your approach would work as you expect if I understand you correctly.

**Comment by wiltbb** [comment]
Thank you，Suhrig.
Now I'm using the reference genome mentioned above,and I have whole-genome sequencing data for more than thousand samples.If there is complete coverage of reads at the breakpoint site,we assume that the fusion gene is a transcription that is newly formed.Do I understand what you mean?

**Comment by suhrig** [comment]
You need matched whole-genome sequencing and RNA-Seq samples from the same specimen. If you detect a structural variant in the WGS data which coincides with the fusion, then the fusion is the product of a genomic rearrangement. If you don't detect a structural variant in the WGS data, then the fusion is probably mediated by splicing (provided that the structural variant caller did not fail to detect the genomic rearrangement). The important bit is that the WGS and RNA samples are matched. You cannot simply take 1000 samples from different donors.

**Comment by wiltbb** [comment]
You're right.Thank you very much.
