### ISSUE TITLE
Aligned.out.bam file empty

### ISSUE THREAD

**Issue by paulwittgenstein** [suhrig/arriba#186]
Hello,
I have an issue with running the STAR alignment command as described on the arriba readthedocs website. The problem is that when I run it as described on the website, I don't get any output. 

Can you help me to find a solution for this? 

The command I ran initially, as taken from the website, was: 

```
  STAR \
      --runThreadN 8 \
      --genomeDir /home/12702668/personal/genomeDir -genomeLoad NoSharedMemory \
      --readFilesIn /home/12702668/personal/fasta_files/ERR947017_1.fastq.gz /home/12702668/personal/fasta_files/ERR947017_1.fastq.gz \--readFilesCommand zcat \
      --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 \
      --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 \
      --chimSegmentMin 10 --chimOutType WithinBAM HardClip --chimJunctionOverhangMin 10 --chimScoreDropMax 30 \
      --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50 |
```

I played around with the parameters and discovered that if I leave out  "outStd BAM_Unsorted", I do get an Aligned.out.bam output. However, it is empty. This is what I ran to get the empty Aligned.out.bam file:

```
STAR \
    --runThreadN 8 \
    --genomeDir /home/12702668/personal/genomeDir --genomeLoad NoSharedMemory \
    --readFilesIn /home/12702668/personal/fasta_files/ERR947017_1.fastq.gz /home/12702668/personal/fasta_files/ERR947017_1.fastq.gz \
    --readFilesCommand zcat --outSAMtype BAM --outSAMunmapped Within --outBAMcompression 0 \
    --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 \
    --chimSegmentMin 10 --chimOutType SeparateSAMold --chimJunctionOverhangMin 10 --chimScoreDropMax 30 \
    --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50 |
```

The files I used to build the genomeDir with are the GENCODE38.gtf and the hg38.fa, downloaded using the ./download_references.sh script. The genomeDir appears correct to me, it contains the files:
 
```
Genome   SA       chrLength.txt  chrNameLength.txt  exonGeTrInfo.tab  geneInfo.tab          sjdbInfo.txt              sjdbList.out.tab
Log.out  SAindex  chrName.txt    chrStart.txt       exonInfo.tab      genomeParameters.txt  sjdbList.fromGTF.out.tab  transcriptInfo.tab 

```
None of them are empty and are in the expected format. 

The fastq files I used are publicly available and downloaded from: 
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR947/ERR947017/ERR947017_1.fastq.gz
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR947/ERR947017/ERR947017_2.fastq.gz

The Log.out file also looks not entirely correct to me: 

[Log.out STAR.txt](https://github.com/suhrig/arriba/files/10908746/Log.out.STAR.txt)

Thank you so much for your help in advance!

**Comment by suhrig** [comment]
Here are a number of things to try:

1. When you run the command from the website, you must make sure to pipe the output of STAR to a file. The parameter `--outStd Bam_Unsorted` instructs STAR to write the alignments to stdout. So you must redirect the output to a file, e.g., `STAR ... --outStd Bam_Unsorted ... > my_file.bam`.

2. You pass the same FastQ file for read1 and read2. The correct usage is `--readFilesIn /home/12702668/personal/fasta_files/ERR947017_1.fastq.gz /home/12702668/personal/fasta_files/ERR947017_2.fastq.gz`. Note the `_2.fastq.gz` in the name of the second file.

3. You have an escape character (`\`) before the parameter `--readFilesCommand`. Most likely this is what causes your problem. It seems STAR gets stuck at reading the input file (because the readFilesCommand is not specified correctly) and simply never even starts to fill the output file `Aligned.out.bam`.

Let me know if this helps.

**Comment by paulwittgenstein** [comment]
Now I get a .bam file! Thanks! I think it was your first suggestions, including ... > my_file.bam that solved it. I wasn't aware  that I have to include this. 
However, another issue came up: the .bam file seems to not have headers, which, to my understanding, are needed to make arriba run.
Arriba gives me the error `ERROR: failed to read SAM header
` , as well as samtools, which tells me `my_file.bam had no targets in header.`
 Do you know how to solve this?

**Comment by suhrig** [comment]
That's odd. Something must still be wrong with your command. Can you paste the full command that you use to generate the file, please?

**Comment by paulwittgenstein** [comment]
This is the code I used: 
`STAR \
    --runThreadN 8 \
    --genomeDir /home/12702668/personal/second_genomeDir --genomeLoad NoSharedMemory --readFilesIn /home/12702668/personal/fasta_files/ERR947017_1.fastq /home/12702668/personal/fasta_files/ERR947017_2.fastq \
    --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 \
    --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 \
    --chimSegmentMin 10 --chimOutType SeparateSAMold --chimJunctionOverhangMin 10 --chimScoreDropMax 30 \
    --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50 \ outStd BAM_Unsorted > my_file.bam |`

And this is the Log.out it gave me: 
[Log.out STAR March 11.txt](https://github.com/suhrig/arriba/files/10949645/Log.out.STAR.March.11.txt)

**Comment by suhrig** [comment]
You are missing a double-dash before `outStd` and the pipe at the end of the command is superfluous. Try the following and let me know if it works or not:

```
STAR --runThreadN 8 --genomeDir /home/12702668/personal/second_genomeDir --genomeLoad NoSharedMemory --readFilesIn /home/12702668/personal/fasta_files/ERR947017_1.fastq /home/12702668/personal/fasta_files/ERR947017_2.fastq --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentMin 10 --chimOutType SeparateSAMold --chimJunctionOverhangMin 10 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50 --outStd BAM_Unsorted > my_file.bam
```

**Comment by paulwittgenstein** [comment]
I tried out your code, and the file still lacks a header (`samtools quickcheck my_file.bam` still puts out `my_file.bam had no targets in header.` . Is there anything else I can try? 


Also, I feel like the ` | ` is necessary when running STAR through sbatch on my university's server, since I get the error message `slurmstepd: error: Detected 1 oom-kill event(s) in step 328090.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
` when I do not include it at the end of a call.

**Comment by suhrig** [comment]
How big is the BAM file that is generated? I suspect it not only lacks a header. More likely, it contains hardly any data.

I recommend the following:

1. Do not call STAR directly. Run the script `run_arriba.sh`. If you absolutely must run STAR directly, then start with the script `run_arriba.sh` and gradually adapt it to suit your needs, making sure that after each modification, it still works. This way you will catch the error that's causing your problems.
2. I just noticed that you used `--chimOutType SeparateSAMold`, which I blindly copy-and-pasted in my suggested command. This works, but it is deprecated. It also requires that `--chimMultimapNmax` must be 0, which is not the case in your command. Again, I recommend to start with the `run_arriba.sh` script and work your way backwards to what you want to have. For optimal fusion calls, I do recommend to stick the STAR parameters given in this demo script and not tamper with them.
3. What slurm is trying to tell you is that you must give your job more memory. STAR needs at least 40GB of RAM. I recommend 60GB. The `|` at the end of your command does not make a lot of sense to be syntactically and the `oom-kill` error is almost certainly unrelated to that.

**Comment by suhrig** [comment]
Do you still need help with this? Or have you managed to remedy the problem?

**Comment by paulwittgenstein** [comment]
Hi, thank you very much for your help! I made everything work. However, there is still one thing that's not absolutely necessary for our study but would still be nice to have: 
Is it possible yo save the Aligned.out.bam and associated files when running multiple files in a for loop in bash? Everytime I try to for instance use cp to copy the output to another place, giving it a more informative name, the loop gives an error and aborts. 
Is there a way to make this work? 
Thank you very much again for your patience and helpfulness!

**Comment by suhrig** [comment]
Can you paste the code of the loop here?

**Comment by paulwittgenstein** [comment]
Sure! the code I used is: 

`#!/bin/sh

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=256GB
#SBATCH --time=1-12
#SBATCH --export=ALL

# align FastQ files (STAR >=2.7.10a recommended)

while read line; do

   long="$line"
   tmpstr="${long}.."
   short="${tmpstr:0:12}" ; echo "${short}"

echo "starting STAR for reads $line"
touch "$short"_test.file.tsv
# get arguments
STAR_INDEX_DIR=/zfs/jacobs/Colette/12702668/second_genomeDir
ANNOTATION_GTF=/zfs/jacobs/Colette/12702668/GENCODE38.gtf
ASSEMBLY_FA=/zfs/jacobs/Colette/12702668/hg38.fa
THREADS=8

STAR \
      	--runThreadN "$THREADS" \
        --genomeDir "$STAR_INDEX_DIR" --genomeLoad NoSharedMemory \
        --readFilesIn $line \
        --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 \
        --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 \
        --chimSegmentMin 10 --chimOutType WithinBAM HardClip --chimJunctionOverhangMin 10 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 \
        --chimMultimapNmax 50 |

tee Aligned.out.bam |


# call arriba
/home/12702668/personal/arriba_v2.4.0/arriba \
        -x /dev/stdin \
        -o "$short"_fusions.tsv -O "$short"_fusions.discarded.tsv \
        -a "$ASSEMBLY_FA" -g "$ANNOTATION_GTF" -f blacklist

# sorting and indexing is only required for visualization
if [[ $(samtools --version-only 2> /dev/null) =~ ^1\. ]]; then
        samtools sort -@ 8 -m 500M -T tmp -O bam Aligned.out.bam > Aligned.sortedByCoord.out.bam
        rm -f Aligned.out.bam
        samtools index Aligned.sortedByCoord.out.bam
else
    	echo "samtools >= 1.0 required for sorting of alignments" 1>&2
fi

echo "all done!"

done < directory.txt
`

**Comment by suhrig** [comment]
It should work if you write `tee "$short"_Aligned.out.bam` instead of `tee Aligned.out.bam`.

**Comment by paulwittgenstein** [comment]
This worked  - what a simple solution. Thank you very much for you kind support & for providing this great program !
