### ISSUE TITLE
General question about breakpoints

### ISSUE THREAD

**Issue by sermare** [suhrig/arriba#187]
If given a pair of genes involved in a fusion. Would the the same gene fusion which is predicted more than once with different breakpoints strengthen the probability of be a true positive or be a result of various genomic aberrations within the same chromosome due to high number of copy number within the cancer cells?

**Comment by suhrig** [comment]
Yes, this assumption is correct! There is just one exception to this rule, where a single gene is involved in multiple fusion calls, but they're all artifacts: The reverse transcription step of library preparation can give rise to such artifacts. However, they are usually easy to distinguish from a real cluster of rearrangements: reverse transcription-mediated artifacts almost always have their breakpoints in the exon body whereas real fusions from a cluster of rearrangements have their breakpoints at exon boundaries for the most part.

Check out the [section about results interpretation in the manual](https://arriba.readthedocs.io/en/latest/interpretation-of-results/). It contains useful info about precisely those to cases (see subsections "Multiple transcript variants" and "Frequent types of false positives") as well as other important cases.
