### ISSUE TITLE
Low number of structural variants

### ISSUE THREAD

**Issue by yasin-uzun** [suhrig/arriba#188]
Hi,

I have a set of tumor derived PDX samples. I ran Arriba on the RNA-Seq data from these samples. The number of structural variants identified by Arriba range around 20 to 30. Is this number typical? I was expecting more (> 100 per sample). I tried different MAX_E-VALUE values when running, but the results didn't change much. Could you please give some advice about this issue? I will appreciate any comment. Thanks.

**Comment by suhrig** [comment]
20-30 isn't unusual. Why do you expect more? Do you have data from another experiment or fusion caller which suggest there should be more?

Just to double-check: This is bulk RNA-Seq data, right? You speak of structural variants which is terminology usually used with DNA-Seq.

There are technical and biological factors which impact the number of fusions:
- How many reads are there in total?
- What is the read length?
- Is it single-end or paired-end?
- Do you have a measure of the duplication rate/estimated library size as computed by Picard or RNASeQC?
- Do you happen to have a measure of the 3'UTR bias of the library?
- What type of cancer is it?
- Is it a PDX of an early stage tumor or late stage?

**Comment by yasin-uzun** [comment]
Thanks so much for the reply. Yes, this is bulk RNA-Seq. I ran SQUID and got around 200 fusions. That was one of the reasons I was expecting more. 
There are about 30 million paired reads per sample. Reads are 150bp length (Left:150, Right:150). Samples are derived from diagnostic ALL specimens.

**Comment by suhrig** [comment]
20-30 fusions in ALL is about what I would expect according to my experience with running Arriba on samples from this disease.

The sequencing depth is still okay with 30MM reads. You may find a few more fusions with higher depths, but not many I'd say. 150bp paired-end is great. Did you use the recommended alignment parameters stated in the manual or the script run_arriba.sh?

> I ran SQUID and got around 200 fusions

I have no experience with this tool. It is not uncommon for different tools to make discrepant fusion calls, unfortunately. It could be that Arriba misses fusions, but it's just as possible that SQUID produces many false positives. Do you happen to have matched whole-genome sequencing samples available? You could call structural variants independently from this data type and compare with the RNA-Seq data to see what percentage of Arriba's vs. SQUID's calls correlate with structural variants. Alternatively, you may want to look at the additional calls from SQUID in IGV and try to judge for yourself whether they are alignment artifacts or real. Oftentimes, it's quite obvious. But it can be difficult if you don't have an experienced eye.

**Comment by suhrig** [comment]
I'm closing this issue for now. Feel free to reopen if you need further advice. As explained, the number of fusions that Arriba found sounds reasonable for ALL. It could be that SQUID produces many false positives or that Arriba has many false negatives. You need orthogonal benchmarking data to find out.
