### ISSUE TITLE
Circos plot Q: How to make the chromosome labels appear clearer?

### ISSUE THREAD

**Issue by jlee110** [suhrig/arriba#19]
In my circos plot, some of the chromosome labels are sort of hidden due to the numerous intrachromosomal fusions, what would you suggest for making the chromosome label stick out?

Is it possible to make the lines connecting the gene label to the chromosomal band longer, or thinner to not hide the chromosome label? Perhaps a different color font for the chromosomal label?

So far I got this parameter to work:
`circos.genomicLabels(geneLabels, labels.column=4, side="outside", cex=fontSize,connection_height = convert_height(20, "mm"))`

But adding the other parameters give me 50 warnings

`circos.genomicLabels(geneLabels, labels.column=4, side="outside", cex=fontSize,connection_height = convert_height(20, "mm"),line_col = par(col="gray"), line_lwd = par(lwd=0.8), line_lty = par(lty=4))`

**Comment by suhrig** [comment]
Drop the `par(...=` and the warnings should disappear:

```
circos.genomicLabels(geneLabels, labels.column=4, side="outside", cex=fontSize,connection_height = convert_height(20, "mm"),line_col="gray", line_lwd=0.8, line_lty=4)
```
What `par(...=` means is that the function will use the default value, which can be set with `par`.

**Comment by jlee110** [comment]
I'm an r-noob, code-noob, basically a caveman. Thank you!!!!!!!!!!!!!!! :+1: 

`circos.genomicLabels(geneLabels, labels.column=4, side="outside", cex=fontSize,connection_height = convert_height(20, "mm"),line_col = c("#DBBE4A"), line_lwd = 0.8, line_lty = 4)`
