### ISSUE TITLE
EOF marker is absent. The input may be truncated

### ISSUE THREAD

**Issue by picardda** [suhrig/arriba#192]
Hello and thank you for generating this tool. I am new at the RNA sequencing alignments and fusion detection, but I am hoping to get your program to work.

I have installed arriba using the command on the website:
wget https://github.com/suhrig/arriba/releases/download/v2.4.0/arriba_v2.4.0.tar.gz
tar -xzf arriba_v2.4.0.tar.gz
cd arriba_v2.4.0 && make 

and then downloaded the reference:
./download_references.sh hs37d5viral+GENCODE19

Everything seems to be fine.  However, when I run arriba as stated in the quickstart:
./run_arriba.sh STAR_index_hs37d5viral_GENCODE19/ GENCODE19.gtf hs37d5viral.fa database/blacklist_hg19_hs37d5_GRCh37_v2.4.0.tsv.gz database/known_fusions_hg19_hs37d5_GRCh37_v2.4.0.tsv.gz database/protein_domains_hg19_hs37d5_GRCh37_v2.4.0.gff3 8 test/read1.fastq.gz test/read2.fastq.gz

I get the following error:
EXITING because of fatal PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions
SOLUTION: re-run with --chimOutType Junctions

Mar 24 09:47:26 ...... FATAL ERROR, exiting
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
(total=ERROR: no normal reads found

I tried to change the run_arriba.sh file to "--chimOutType Junctions", but I received an error that made me change it back.

Is there anything you could suggest I try?  Not sure if it is important, but I am running STAR 2.7.3a.
Thank you for your help,
Daniel

**Comment by suhrig** [comment]
Your STAR version is too old. The minimum requirement is >= 2.7.6a. However, I recommend >=2.7.10a, because there are some good improvements for fusion detection coming with this version.
