### ISSUE TITLE
Error downloading reference data

### ISSUE THREAD

**Issue by pagnasok** [suhrig/arriba#193]
Hello, I'm running the download_references.sh script for hg38+GENCODE38 but I keep running into the error below.
Any ideas on how to resolve this? Thanks!

Downloading assembly: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.chromFa.tar.gz
Downloading annotation: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz
Apr 18 13:09:56 ..... started STAR run
Apr 18 13:09:56 ... starting to generate Genome files
Apr 18 13:11:19 ... starting to sort Suffix Array. This may take a long time...
Apr 18 13:11:46 ... sorting Suffix Array chunks and saving them to disk...
Apr 18 14:11:17 ... loading chunks from disk, packing SA...

EXITING because of FATAL problem while generating the suffix array
The number of indices read from chunks = 4694512436 is not equal to expected nSA=6098631566
SOLUTION: try to re-run suffix array generation, if it still does not work, report this problem to the author

**Comment by suhrig** [comment]
Did one of my suggested solutions work?

**Comment by pagnasok** [comment]
Hi, sorry for the delayed reply! But yes it was a disk space issue. Thanks!
