### ISSUE TITLE
Split reads evidence for EWSR1-NR4A3 fusion missing in sample.arriba.fusions.discarded.tsv

### ISSUE THREAD

**Issue by bioPG** [suhrig/arriba#196]
Title: Missing record for EWSR1-NR4A3 fusion in sample.arriba.fusions.discarded.tsv

Issue Description:
I have observed split reads indicating the presence of the EWSR1-NR4A3 fusion in my BAM file. However, I noticed that there are no records related to this fusion in the sample.arriba.fusions.discarded.tsv file generated by the tool.

Details:
- aligner: STAR
- Arriba version: 2.4.0
- Command-line parameters used: I used the recommended command-line parameters suggested by Arriba for fusion analysis.
- Observation of split reads: 
![image](https://github.com/suhrig/arriba/assets/44594049/64f1c319-6788-4f9a-bf4e-c6fb4b440f35)

Expected Outcome:
I expected to find the EWSR1-NR4A3 fusion listed in the sample.arriba.fusions.discarded.tsv file since split reads indicating its presence were observed in the BAM file.

Possible Explanations:
1. Filtering criteria: It is possible that Arriba applied certain filtering criteria during the fusion analysis, leading to the exclusion of the EWSR1-NR4A3 fusion from the discarded fusion list. I would appreciate clarification on the specific filtering criteria used and why this fusion was excluded.
2. Parameters or settings: There is a possibility that I missed specifying some parameters or settings during the Arriba run, which might have caused the fusion to be omitted from the discarded list. Please advise on any specific parameters that could affect fusion detection.

Additional Information:
If there are any additional details, logs, or suggestions that could help resolve this issue, please let me know. I am eager to understand the discrepancy and would greatly appreciate any guidance or assistance you can provide.

Thank you for your attention to this matter.

**Comment by suhrig** [comment]
Sorry for not getting back to you right away. Why did you close this issue? Did you find the reads after all?

**Comment by bioPG** [comment]
Sorry, I forgot to reply to you. After carefully investigating the issue, I discovered that all the reads in my fastq file were duplicated. This might have occurred when the upstream personnel merged the data and mistakenly included the same file multiple times. After removing the duplicate reads, the EWSR1-NR4A3 fusion was detected, and then I closed the issue.
