### ISSUE TITLE
Validating New Versions

### ISSUE THREAD

**Issue by cpsosa** [suhrig/arriba#197]
Hello,  I was comparing the output from arrivals 4.1 versus 4.4 and I noticed that there are some differences in these two when comparing Arriba_fusions.tsv.

How do you validate a new release of arrivals?

Thanks,

**Comment by cpsosa** [comment]
typo: it is arrival and not arrivals in the above message.

**Comment by cpsosa** [comment]
arriba

**Comment by suhrig** [comment]
> 4.1 versus 4.4

I assume you meant version 2.4 vs. 2.1.

> How do you validate a new release of arrivals?

Every change to Arriba's code is tested on ~300 samples with a total of ~10000 fusions, of which ~3000 have been validated experimentally or confirmed by a matched whole genome sequencing sample. The validation samples originate from various sequencing centers/publications and include different library preparation protocols and a broad range of malignancies to avoid overfitting to a specific type of samples. Before committing the change, I make sure that it improves Arriba's predictions.

P.S. You can edit a post by clicking on the the dots in the upper right corner of the post.

**Comment by cpsosa** [comment]
Thank you Suhrig for your prompt reply and help.  Yes, sorry I meant these versions https://github.com/suhrig/arriba/releases.

OK, since each release tries to include improvements or other changes that introduces the differences I see.  Thank you.
