### ISSUE TITLE
Giving known fusions list does not recover the fusions I want

### ISSUE THREAD

**Issue by acloop62hz** [suhrig/arriba#199]
For the `-k` known fusions list parameter, I found that Arriba cannot recover many of the fusions in the given list. For these fusions, I found they have one thing in common: they don't have read identifiers, however plenty of them have number of split read >=2. I wonder if read identifiers should include split reads and why there can be cases where a fusion with >= split reads(1 or 2) have "." in the read identifiers column.
Thanks in advance!

**Comment by suhrig** [comment]
By default, Arriba does not report read identifies in the discarded output file. You must run it with the extra parameter `-X`. Did you use this parameter?

**Comment by acloop62hz** [comment]
Running arriba with parameter `-x` does give me read identifiers, thanks for your reply! 
I'm also a little bit curious about if arriba only recovers fusions discarded by certain filters (relative_support and min_support)?  If so, is there a specific reason to choose those two filters? Sorry for any disruption caused by my inquiries, thanks for your time!

**Comment by suhrig** [comment]
Yes, Arriba only recovers known fusions that were removed by a selection of filters. It only considers filters that are *often* right, but not always. The filters `relative_support` and `min_support` tend to be wrong with low-quality samples or when the fusion is expressed at a low level.

**Comment by acloop62hz** [comment]
I see, thank you so much!
