### ISSUE TITLE
request for simulation dataset mentioned in the paper

### ISSUE THREAD

**Issue by acloop62hz** [suhrig/arriba#200]
Hi @suhrig ,
I'm very interested in this software and I'm trying to rerun Arriba on the simulation dataset from Jia. et al mentioned in the paper. I have tried to access the dataset from Jia's paper but unfortunately the link seems to be broken. I hope you don't mind me asking, but would it be possible for you to share a copy of the dataset with me? I would really appreciate your help and generosity.

Thank you very much for your time and attention.
Yuxuan

**Comment by suhrig** [comment]
The files are still available on the Internet Archive (bless this site!): https://web.archive.org/web/20160106213835/http://public.genomics.org.cn/BGI/soap/SOAPfuse/simulate_seq-data.for.SOAPfuse.tar.gz

The SourceForge page of SOAPfuse is also still up and has some info on the benchmark dataset: https://sourceforge.net/p/soapfuse/wiki/Performance_Evaluation/

**Comment by acloop62hz** [comment]
There seems to be network error when downloading the dataset. I guess Internet Archive lost the dataset part. Thanks so much anyway! I really appreciate your help.
