### ISSUE TITLE
Recommended STAR index version

### ISSUE THREAD

**Issue by cpsosa** [suhrig/arriba#209]
Hi Suhrig,

We would like to use arriba v2.4.0 with STAR 2.7.8a.  What versions of the STAR reference index do you recommend?  Do you have the command/options suggested to build the index?

Thanks,

**Comment by suhrig** [comment]
You can use the script `download_references.sh` to download the reference files and build the STAR index. I recommend `GRCh38+GENCODE38`. If you are also interested in detecting viral integration sites, you can use `GRCh38viral+GENCODE38`. Run the script without any options to see all available reference files.

Does this answer your question?

I should note that STAR >=2.7.10a is recommended for use with Arriba. Version 2.7.8a works, but you will not be able to detect fusions from multi-mapping reads. There is a small number of known cancer driver fusions that will be missed.

In case you have not found it yet, here is the quickstart guide, which may contain some more useful bits of information: https://arriba.readthedocs.io/en/latest/quickstart/

**Comment by cpsosa** [comment]
Thank you.  Very useful information that we'll read carefully.  We use hg19
but there is also info about hg19, I believe from what I briefly read.

Thanks,

**Comment by cpsosa** [comment]
Sorry, I forgot to add.  We only use hg19 so we need hg19.

**Comment by suhrig** [comment]
> How can we download the container image to local?

You can convert the docker image to a local singularity image using the following command:

```
sudo singularity build arriba-2.4.0.sif docker://uhrigs/arriba:2.4.0
```

> Does the container do the star alignment itself?

Yes, it does. It uses optimized alignment parameters for fusion detection, which improves detection a bit. Let me know if you prefer to do the alignment yourself. There is a way to bypass the built-in alignment.

> We only use hg19 so we need hg19.

Take a look at the [singularity-based installation](https://arriba.readthedocs.io/en/latest/quickstart/#installation-using-singularity) and use `hg19+GENCODE19` as an argument.

**Comment by cpsosa** [comment]
Thank you, I'll forward this to the installers.

**Comment by suhrig** [comment]
Which version of singularity do you use? This should work ...

**Comment by suhrig** [comment]
Are you still looking for a solution? This should work. Maybe you're using an incompatible version of Singularity. I could do some tests if you tell me your version.

**Comment by cpsosa** [comment]
Hi Suhrig,

It works, thanks for checking.
