### ISSUE TITLE
error: Command 'arriba' not found, did you mean: command 'ariba' from deb ariba (2.14.6+ds-3build1)

### ISSUE THREAD

**Issue by jdjdj0202** [suhrig/arriba#212]
Hi, 
I wanted to run commands to get output files.
I entered arriba_v2.4.0 directory and wrote following command lines:

ubuntu@ip-ooo-oo-oo-oo:~/arriba_v2.4.0$ arriba /home/ubuntu/RNA/ATL005.Aligned.sortedByCoord.out.bam \
       -g /home/ubuntu/arriba_v2.4.0/GENCODE38.gtf -a /home/ubuntu/arriba_v2.4.0/hg38.fa \
       -b /home/ubuntu/arriba_v2.4.0/database/blacklist_hg38_GRCh38_v2.4.0.tsv -k k/home/ubuntu/arriba_v2.4.0/database/known_fusions_hg38_GRCh38_v2.4.0.tsv \
       -p /home/ubuntu/arriba_v2.4.0/database/protein_domains_hg38_GRCh38_v2.4.0.gff3 \
       -o /home/ubuntu/ATL005_RNAfusions.tsv -O /home/ubuntu/ATL005_fusions.discarded.tsv

Error message was as follows:
Command 'arriba' not found, did you mean:
  command 'ariba' from deb ariba (2.14.6+ds-3build1)
Try: sudo apt install <deb name>

How can I solve this problem?
Please help me.
Thanks.

**Comment by suhrig** [comment]
You either need to add the installation directory of Arriba to your `$PATH` environment variable or run it as `./arriba ...` from the local directory. That should do the trick. Let me know if not.
