### ISSUE TITLE
Can  I use the latest Gencode GTF file ?

### ISSUE THREAD

**Issue by JeWeizhong** [suhrig/arriba#216]
Can I use the latest Gencode GTF file, which is different from the link provided in the 'download_references.sh GENCODE19.' ? I would like to use the file from this URL: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh37_mapping/gencode.v44lift37.annotation.gtf.gz. This file includes some new genes.

But I'm concerned that this file may not match the software's blacklist and protein domains or other configuration files.

**Comment by suhrig** [comment]
Yes, you can use it. The blacklist and known fusions files are independent from the annotation. They don't use gene names. Some protein domains will fail to map, but it should be a minority, and this is also the case with GENCODE19.
