### ISSUE TITLE
Arriba output filtering

### ISSUE THREAD

**Issue by teresa1997** [suhrig/arriba#219]
Hi, we are running arriba and we want to filter the output file to reduce the number of false positive. We are setting this condition for the columns in the output file: 
`
split_reads1+split_reads2>=5 OR
discordant_mates>=5 OR
split_reads1+split_reads2+discordant_mates>=5
`

Do you think it makes sense? Because in your guidlines you write that >10 supporting reads is sufficient, then you write even predictions with just 2-5 reads can be correct. 
Which could be the best filtering approach in your idea? Should I integrate also the coverage? If yes, how?

This is how I'm running arriba: 
```
singularity exec \
        -B /path/$i:/output \
        -B /path:/references:ro \
        -B /path/$i/trimmed1.fastq.gz:/read1.fastq.gz:ro \
        -B /path/$i/trimmed2.fastq.gz:/read2.fastq.gz:ro \
        docker://uhrigs/arriba:2.4.0 \
        arriba.sh
```

Thank you

**Comment by suhrig** [comment]
Hi Teresa,

The easiest way to improve the sensitivity/specificity tradeoff is to remove fusion predictions with confidence "low". The majority of them are false positives. These candidates are only reported for users with a demand for high sensitivity. For many use cases the medium- & high-confidence fusions are sufficient.

To some degree, the filters you mention are already reflected in the confidence scoring. Removing low-confidence fusions will eliminate a lot of fusions with less than 5 supporting reads. It will also eliminate many fusions with few supporting reads relative to the coverage. That being said, it is still possible to get rid of some more false positives by explicitly selecting for fusions with more than 5 supporting reads (or even more) and by requiring that the sum of the split reads and discordant mates must be greater than a certain percentage of the sum of the coverages shown in the columns `coverage1/2` (say 1% or 2%).

Do you see a pattern in the false positives? For example, have you seen [the section on frequent false positives in the manual](https://arriba.readthedocs.io/en/stable/interpretation-of-results/#frequent-types-of-false-positives)? What could be more effective than selecting for a minimum number of reads is to remove false positives with a certain pattern. This could go as far as writing a new filter for Arriba. If you can share a sample that has many false positives, I may come up with a method to remove them and incorporate it into Arriba. In my experience, samples from certain sources often harbor a unique type of false positives. Arriba's filters may not be prepared for this. If I had a few examples of such samples, I could develop a filter. This is often more accurate than a crude read count filter.

Are you aware of any peculiarities of your data that may explain the false positives? For example, is it targeted data or very deep sequencing or single cell sequencing?

Regards,
Sebastian

**Comment by teresa1997** [comment]
Hi Sebastian,
thank you for your answer and kindness. 
Yes, I've seen the section on frequent false positives. My data are RNA-seq data of 100 million fragments per sample. They are coltured cell lines from a primary tumor, we cannot exclude chromosomic instability. 

Now, I came up with another issue. 
I ran ARRIBA with the version v2.1.0 with this code

```
run_arriba.sh \
$genome_folder/STAR_index_GRCh38viral_GENCODE36 \ 
$genome_folder/GENCODE36.gtf \
$genome_folder/GRCh38viral.fa \
arriba/var/lib/arriba/blacklist_hg38_GRCh38_v2.1.0.tsv.gz \
arriba/var/lib/arriba/known_fusions_hg38_GRCh38_v2.1.0.tsv.gz \
arriba/var/lib/arriba/protein_domains_hg38_GRCh38_v2.1.0.gff3 25 \
$input_fastq/$i/$i.trimmed1.fastq.gz \
$input_fastq/$i/$i.trimmed2.fastq.gz
```

And then I run ARRIBA version v2.4 with this code
```
singularity exec \
        -B /path/$i:/output \
        -B /path:/references:ro \
        -B /path/$i/trimmed1.fastq.gz:/read1.fastq.gz:ro \
        -B /path/$i/trimmed2.fastq.gz:/read2.fastq.gz:ro \
        docker://uhrigs/arriba:2.4.0 \
        arriba.sh
```

I compare the results and see that only about 40% of the variants are in common between the two runs. In this run I'm using this version of the reference genome: GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play. 
In the first run we didn't use singularity, instead now yes. 
Is there something you have changed in the STAR parameter or are these differences just due to the different versions of the tool and reference?
If you provide me with an email address I can send you a sample.

Thank you,
Teresa

**Comment by suhrig** [comment]
The differences are probably explained by the different reference files and different Arriba versions (2.1.0 vs. 2.4.0). I expect most of the differences to be among the low-confidence fusions.

Happy to take a look at your sample if you can send it to s.uhrig [at] dkfz [dot] de.

**Comment by teresa1997** [comment]
Thank you very much!
I have one last question. If I run ARRIBA with docker as above, will it automatically take the blacklist, cytobans and protein domains file? They are all in the reference directory. 

Thank you, Teresa

**Comment by suhrig** [comment]
Yes, it should. Have a look at the status updates that Arriba prints while it's running to confirm.
