### ISSUE TITLE
Issue with Dragen BAM encountering std::out_of_range error in version [v2.4.0]

### ISSUE THREAD

**Issue by avilaHugo** [suhrig/arriba#232]
Dear developers,

I hope this message finds you well. I am reaching out to report a bug encountered while using the latest arriba v2.4.0. Upon utilizing the Dragen pipeline with version (dragen Version 07.021.624.3.10.9), it appears that the BAM file encounters some compatibility issues.

A similar issue has been previously reported here: [link to the issue](https://github.com/suhrig/arriba/issues/179). I did try to pull [this debug image](https://github.com/suhrig/arriba/issues/179#issuecomment-1369480162) but it seems that it is not available anymore.

To provide more clarity, I've outlined the steps to reproduce the error below:

### Steps to Reproduce:
1. Command line execution of Arriba `CL.sh`:

```bash
#!/usr/bin/env bash

inputBam="bam/error_sample_anon.bam"
outputFileNamePrefix="error_sample_anon/arriba"
filters="top_expressed_viral_contigs,viral_contigs,low_coverage_viral_contigs,uninteresting_contigs,no_genomic_support,short_anchor,select_best,many_spliced,long_gap,merge_adjacent,hairpin,small_insert_size,same_gene,genomic_support,read_through,no_coverage,mismatches,homopolymer,low_entropy,multimappers,inconsistently_clipped,duplicates,homologs,blacklist,mismappers,spliced,relative_support,min_support,known_fusions,end_to_end,non_coding_neighbors,isoforms,intronic,in_vitro,intragenic_exonic,internal_tandem_duplication"
knownfusions="/dados/arriba_resources/known_fusions_hg19_hs37d5_GRCh37_v2.4.0.tsv.gz"
genome="/dados/arriba_resources/Homo_sapiens.GRCh37.75.genome.fa"
gencode="/dados/arriba_resources/gencode.v19.annotation.gtf.gz"
blacklist="/dados/arriba_resources/blacklist_hg19_hs37d5_GRCh37_v2.4.0.tsv.gz"
domains="/dados/arriba_resources/protein_domains_hg19_hs37d5_GRCh37_v2.4.0.gff3"

/arriba*/arriba \
     -x $inputBam \
     -o $outputFileNamePrefix".fusions.tsv" -O $outputFileNamePrefix".fusions.discarded.tsv" \
     -k $knownfusions \
     -f $filters \
     -a $genome -g $gencode -b $blacklist -p $domains
```

2. Command line execution of Docker:

```bash
#!/usr/bin/env bash

IMAGE_NAME='uhrigs/arriba:2.4.0'

docker run \
    --user $(id -u):$(id -g) \
    --rm \
    -it \
    -v $PWD:$PWD \
    -v /dados/arriba_resources/:/dados/arriba_resources/:ro \
    -w $PWD \
    "${IMAGE_NAME}" bash -c 'bash CL.sh |& tee error_sample_anon/error_sample_anon.run.log'
```

3. Sample of the error (please refer to the attached log for the complete details):

```bash
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
CL.sh: line 17:     9 Aborted                 (core dumped) /arriba*/arriba -x $inputBam -o $outputFileNamePrefix".fusions.tsv" -O $outputFileNamePrefix".fusions.discarded.tsv" -k $knownfusions -f $filters -a $genome -g $gencode -b $blacklist -p $domains
```

Your assistance in addressing this matter would be greatly appreciated. Please let me know if you require any further information from my end.

Best regards,

[error_sample_anon.tar.gz](https://github.com/suhrig/arriba/files/14301025/error_sample_anon.tar.gz)

**Comment by suhrig** [comment]
Sorry you are having issues running the tool on Dragen.

The bug seems more related to issue #221, since it happens in the last step (output fusions) and not in the mismappers filter (as in the issue you linked). I have fixed the bug in issue #221 in the develop branch of Arriba. Could you please try if this works for you, too? Here is how to download and compile the development version:

```
git clone https://github.com/suhrig/arriba.git
cd arriba
git checkout develop
make
```

If that does not help, then you can either send me a test file (which I'm guessing is not possible due to data protection) or I can send you instruction on how to run Arriba in debug mode and you send me the full stack trace so I see exactly at with point the error is triggered.

Related question: I see that you disabled all of Arriba's filters. What's the motivation behind this? You might as well run it with the standard filters enabled, which will give you a prefiltered list of high-confidence fusions, and fish for any potentially missed fusions in the discarded file.

**Comment by suhrig** [comment]
Have you had a chance yet to try out if the dev version fixes your problem?

**Comment by avilaHugo** [comment]
Hello, sorry for the delayed response; I had other urgent tasks to attend to.

I tried the development version and encountered the same issue. I can provide you with a few BAM files where the problem occurs. How would you like me to send these files? Can I create a personal link for an S3 bucket for you?

Regarding the filters, I consulted with my colleague, and she informed me of the following:

"After several tests, we decided to remove all filters. This decision was made because some fusion events, identified by Dragen and relevant to our research, were being filtered out. We need to report these events regardless and require all pertinent information, such as reading_frame and retained_protein_domains."

**Comment by suhrig** [comment]
Sending me the BAM files would be extremely helpful. A personal HTTPS link to S3 should work. You can send the link to sebastian (dot) uhrig (at) gmail (dot) com

**Comment by avilaHugo** [comment]
Hi there,

I've sent the email with the requested BAM file. Currently, I've provided one BAM file that illustrates the mentioned issue. However, if you need more files for further analysis or testing, please let me know, and I'll be glad to send them.

Also, I'd like to inform you that I've removed the original sample name from the BAM file using samtools and sed. While I don't anticipate any issues resulting from this modification, the file is no longer identical to the one output by Dragen due to this alteration. I ran the debug version with this anonymized BAM file and encountered the same error mentioned above.

**Comment by suhrig** [comment]
I have just pushed a fix to the `develop` branch. Can you give it a try, please? As before, this is the procedure to build the development version:

```
git clone https://github.com/suhrig/arriba.git
cd arriba
git checkout develop
make
```

**Comment by avilaHugo** [comment]
Hello, I tried using two other problematic files, and it appears that the issue has been resolved. Thank you!

By the way, in case anyone needs a Docker development image, the following worked for me: 

```bash
FROM ubuntu:focal
MAINTAINER Sebastian Uhrig @ DKFZ

# install dependencies
RUN export DEBIAN_FRONTEND=noninteractive && \
apt-get update -y && \
apt-get install -y --no-install-recommends git build-essential wget ca-certificates samtools r-base r-cran-circlize r-bioc-genomicalignments r-bioc-genomicranges libxml2

# install version of STAR that supports --chimMultimapNmax and --chimOutType WithinBAM
RUN wget -qO - 'https://github.com/alexdobin/STAR/archive/2.7.10a.tar.gz' | \
tar --strip-components=3 -C /usr/local/bin -xzf - 'STAR-2.7.10a/bin/Linux_x86_64/STAR'

# install arriba
# RUN wget -qO - 'https://github.com/suhrig/arriba/releases/download/v2.4.0/arriba_v2.4.0.tar.gz' | tar -xzf - --exclude='arriba*/.git'
RUN git clone --depth 1 --branch develop https://github.com/suhrig/arriba.git \
    && cd arriba \
    && make \
    && cd -

# make wrapper script for download_references.sh
RUN echo '#!/bin/bash\n\
cd /references\n\
/arriba*/download_references.sh $1 && \\\n\
ASSEMBLY=$(sed -e "s/viral+.*//" -e "s/+.*//" <<<"$1") && \\\n\
cp /arriba*/database/*$ASSEMBLY* /references' > /usr/local/bin/download_references.sh && \
chmod a+x /usr/local/bin/download_references.sh

# make wrapper script for run_arriba.sh
RUN echo '#!/bin/bash\n\
cd /output && \\\n\
/arriba*/run_arriba.sh /references/STAR_index_* /references/*.gtf /references/*.fa /references/blacklist_*.tsv.gz /references/known_fusions_*.tsv.gz /references/protein_domains_*.gff3 ${THREADS-8} /read1.fastqchmod a+x /usr/local/bin/arriba.sh

# make wrapper script for draw_fusions.R
RUN echo '#!/bin/bash\n\
Rscript /arriba*/draw_fusions.R --annotation=$(ls /references/*.gtf) --fusions=/fusions.tsv --output=/output/fusions.pdf --proteinDomains=$(ls /references/protein_domains_*.gff3) --alignments=/Aligned.sortedBychmod a+x /usr/local/bin/draw_fusions.sh
```

**Comment by suhrig** [comment]
Awesome! Thanks for the great feedback and even more so for reporting the issue in the first place!

The issue was that Dragen hard-clipped some reads, where Arriba did not expect it. Namely, Arriba only expects supplementary alignments to be hard-clipped, but Dragen also hard-clips multi-mapping reads. Some other conditions also need to be met to trigger the bug. In total, only six reads were affected in your sample, so fairly rare. The fix was to discard those reads.
