### ISSUE TITLE
Error occured while I running draw_fusion.R

### ISSUE THREAD

**Issue by Zhengfy1022** [suhrig/arriba#233]
I run arriba 2.4.0 with an RNA-Seq sample, which detect a PML::RARA fusion. But when I grep this fusion from sample.fusions.tsv and use this tsv file to run draw_fusion.R , it occured error below:

Loading annotation
Read 2597292 records
Warning in parseGtfAttribute("exon_number", exons) :
  Failed to parse 'exon_number' attribute of 8 record(s).
Loading protein domains
Read 126870 records
Drawing fusion #1: PML:RARA
Error in if (transcriptSelection == "provided" && transcriptId != "." &&  :
  需要TRUE/FALSE值的地方不可以用缺少值
Calls: findExons
停止执行

Here is my command :
${Bin}/Rscript ${PATH}/arriba_v2.4.0/draw_fusions.R \
--fusions=${sample}_PML-RARA.tsv \
--alignments=${sample}.bam \
--output=${sample}_fusion_PML-RARA.pdf \
--annotation=gencode.v19.annotation.gtf \
--cytobands=cytobands_hg19_hs37d5_GRCh37_v2.4.0.tsv \
--proteinDomains=protein_domains_hg19_hs37d5_GRCh37_v2.4.0.gff3

Here is the greped tsv file: ${sample}_PML-RARA.tsv :
#gene1  gene2   strand1(gene/fusion)    strand2(gene/fusion)    breakpoint1     breakpoint2     site1   site2   type    direction1      direction2split_reads1    split_reads2    discordant_mates        coverage1       coverage2       confidence      closest_genomic_breakpoint1     closest_genomic_breakpoint2       filters fusion_transcript       reading_frame   peptide_sequence        read_identifiers
PML     RARA    +/+     +/+     15:74325755     17:38504568     splice-site     splice-site     translocation   downstream      upstream        8850      49      852     460     high    .       .       duplicates(87),mismatches(1)    TGCTACGCCTCGGACCAGGAGGTGCTGGACATGCACGGTTTCCTGCGCCAGGCGCTCTGCCGCCTGCGCCAGGAGGAGCCCCAGAGCCTGCAAGCTGCCGTGCGCACCGATGGCTTCGACGAGTTCAAGGTGCGCCTGCAGGACCTCAGC...GAAAG___ATGCAGCTGTATCCAAGAAAGCCAGCCCAGAGGCTGCCAGCACTCCCAGGGACCCTATTGACGTTGACCTG___GATGTCTCCAATACAACGACAGCCCAGAAGAGGAAGTGCAGCCAGACCCAGTGCCCCAGGAAGGTCATCAAGATGGAGTCTGAGGAGGGGAAGGAGGCAAGGTTGGCTCGGAGCTCCCCGGAGCAGCCCAGGCCCAGCACCTCCAAGGCAGTCTCACCACCCCACCTGGATGGACCGCCTAGCCCCAGGAGCCCCGTCATAGGAAGTGAGGTCTTCCTGCCCAACAGCAACCACGTGGCCAGTGGCGCCGGGGAGGCAG|CCATTGAGACCCAGAGCAGCAGTTCTGAAGAGATAGTGCCCAGCCCTCCCTCGCCACCCCCTCTACCCCGCATCTACAAGCCTTGCTTTGTCTGTCAGGACAAGTCCTCAGGCTACCACTATGGGGTCAGCGCCTGTGAGGGCTGCAAG___GGCTTCTTCCGCCGCAGCATCCAGAAGAACATGGTGTACACGTGTCACCGGGACAAGAACTGCATCATCAACAAGGTGACCCGGAACCGCTGCCAGTACTGCCGACTGCAGAAGTGCTTTGAAGTGGGCATGTCCAAGGAGT___CTGTGAGAAACGACCGAAACAAGAAGAAGAAGGAGGTGCCCAAGCCCGAGTGCTCTGAGAGCTAC...TGGGGGAGCTCATTGAGAAGGTGCGCAAAGCGCACCAGGAAACCTTCCCTGCCCTCTGCCAGCTGGGCAAATACACTACG___AACAACAGCTCAGAACAACGTGTCTCTCTGGACATTGACCTCTGGGACAAGTTCAGTGAACTCTCCACC  in-frame        KDAAVSKKASPEAASTPRDPIDVDLDVSNTTTAQKRKCSQTQCPRKVIKMESEEGKEARLARSSPEQPRPSTSKAVSPPHLDGPPSPRSPVIGSEVFLPNSNHVASGAGEA|aIETQSSSSEEIVPSPPSPPPLPRIYKPCFVCQDKSSGYHYGVSACEGCKGFFRRSIQKNMVYTCHRDKNCIINKVTRNRCQYCRLQKCFEVGMSKESVRNDRNKKKKEVPKPECSES      .

Then I run this sample with arriba 1.2.0 ,it works. 

Why does arriba 2.4.0 not work?
How can i get the right way to deal with this problem?
Thank you so much.

**Comment by suhrig** [comment]
The fusion file is missing the columns `transcript_id1` and `transcript_id2`. Are you sure you created this file with Arriba 2.4.0? The format looks like it was created with an older version.

**Comment by Zhengfy1022** [comment]
Oh I see, I run this sample with arriba2.4.0, it works! I will close this issue later. Thank you so much for your reply.
