### ISSUE TITLE
The interpretation of the contents of the result file fusions.tsv.

### ISSUE THREAD

**Issue by jiaanqiang** [suhrig/arriba#238]
Hi,

Thank you for developing such a great tool.

The content in the last column of the result file fusions.tsv, labeled as "read_identifiers," refers to what? Does it denote the number of reads aligned to the fusion_transcript?

Thanks!

Sincerely,
AQ. J

**Comment by suhrig** [comment]
It's a comma-separated list of the names of all of the reads that support the fusion.

Arriba does not perform an extra alignment of reads to fusion transcripts. It mereley takes the alignments from STAR (which aligns against the wild-type transcripts). But roughly speaking, yes, it's as you say an approximation of "the number of reads aligned to the fusion_transcript".

**Comment by jiaanqiang** [comment]
OK, thank you for your reply.
