### ISSUE TITLE
can't install through conda

### ISSUE THREAD

**Issue by Dagsbio** [suhrig/arriba#24]
I am getting this error over and over again:
---
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
---

**Comment by suhrig** [comment]
Hi David,

I'm sorry you are having trouble installing Arriba using bioconda. I am currently on vacation and therefore cannot try out myself whether the installing procedure has stopped working recently. I'll be back in 1.5 weeks. Until then, can you send me the version of conda you are using? And have you tried resetting your channels to the default ones?

Regards,
Sebastian

**Comment by Dagsbio** [comment]
Hi Sebastian, thanks for your quick reply.

My conda version is 4.7.10 and I managed to install it manually so didn't go further on this.
