### ISSUE TITLE
how to visualize arriba results for a cohort?

### ISSUE THREAD

**Issue by complexgenome** [suhrig/arriba#244]
Hi there,
Thank you for this tool.
I see that there's a script to create visualization - draw_fusion.R. This is per-sample. https://arriba.readthedocs.io/en/latest/command-line-options/#draw_fusionsr 
I'm interested to create visualization for a cohort, that consists several samples. How do I achieve this?

May I simply merge/concat the arriba fusion results into one file to feed into the draw script?
There's little information about cohort analysis. https://arriba.readthedocs.io/en/latest/interpretation-of-results/

**Comment by suhrig** [comment]
Yes, you can put as many fusions as you like into a single file. They don't have to be from the same sample. draw_fusions.R then creates a single PDF file. Just beware that the circos plot includes all fusions in the input file. But this may actually make sense for cohort analyses, too. It will then show the fusions of the whole cohort (unless you use ``--minConfidenceForCircosPlot=none).

The documentation on cohort analyses is a bit thin, true. The reason being that it comes *downstream* of the purpose of Arriba. Also, it's a complex subject and not within the scope of the Arriba documentation.
