### ISSUE TITLE
Proper use of short_anchor

### ISSUE THREAD

**Issue by cpsosa** [suhrig/arriba#246]
I am using -A to set the short_anchor but I do not see changes in the fusion supporting reads ( split_reads1    split_reads2    discordant_mates        coverage1       coverage2 ).

Am I missing additional information?

Thanks

**Comment by suhrig** [comment]
Which values did you try? If you set it high enough, you should see fusions disappearing.

Arriba measures the longest distance from the fusion breakpoint to the furthest aligned base of a fusion-supporting read. If the distance is smaller than the given threshold, the fusion is discarded. 

There is usually no need to tinker with this parameter. May I ask what is your motivation to change it?

**Comment by cpsosa** [comment]
-A 10
-A 30
-A 60

These are the values I tried around the default of 23 bp.
KIAA1549        BRAF    -/-     -/-     chr7:138552721  chr7:140487384  CDS/splice-site CDS/splice-site duplication     11      10      3       2463    5806
KIAA1549        BRAF    -/-     -/-     chr7:138552721  chr7:140487384  CDS/splice-site CDS/splice-site duplication     11      10      3       2463    5806
KIAA1549        BRAF    -/-     -/-     chr7:138552721  chr7:140487384  CDS/splice-site CDS/splice-site duplication     11      10      3       2463    5806
KIAA1549        BRAF    -/-     -/-     chr7:138552721  chr7:140487384  CDS/splice-site CDS/splice-site duplication     11      10      3       2463    5806   <----- DEFAULT

**Comment by cpsosa** [comment]
My motivation was to try to increase the number of supporting reads.

**Comment by cpsosa** [comment]
This particular fusion has a low number of supporting reads.

**Comment by suhrig** [comment]
I see. This parameter won't help you. Increasing the number of supporting reads is only possible when you see a value in the `filters` column with a number next to it in parentheses. These are all the reads that are visible to Arriba.

Otherwise, you need to optimize the STAR alignment parameters.

**Comment by suhrig** [comment]
If you like, I can offer my help to try to improve the parameters. I will need the FastQ files for this, though.

**Comment by cpsosa** [comment]
Thanks!  This answers my question.
