### ISSUE TITLE
std::bad_alloc when running ./download_references.sh

### ISSUE THREAD

**Issue by Dagsbio** [suhrig/arriba#25]
Full Error:

dags@bio:~/Desktop/FUSIONS/arriba_v1.1.0$ ./download_references.sh hg19+GENCODE19
Downloading assembly: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/bigZips/chromFa.tar.gz
Downloading annotation: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
Jul 30 10:43:59 ..... started STAR run
Jul 30 10:43:59 ... starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./download_references.sh: line 111:  7880 Aborted                 (core dumped) STAR --runMode genomeGenerate --genomeDir STAR_index_${ASSEMBLY}_${ANNOTATION} --genomeFastaFiles "$ASSEMBLY.fa" --sjdbGTFfile "$ANNOTATION.gtf" --runThreadN "$THREADS" --sjdbOverhang 200

**Comment by suhrig** [comment]
The genome generation step of STAR requires 30-40 GB of RAM. Does your machine have sufficient memory? If you can rule out that this is the issue, can you send me the log files of STAR?

**Comment by Dagsbio** [comment]
Oh yes so definitely that's the problem, thanks!
