### ISSUE TITLE
Coverage and supporting reads

### ISSUE THREAD

**Issue by YinYangKarly** [suhrig/arriba#253]
I have a question regarding the arriba results interpretation. In the documentation of arriba it is stated:
"`coverage1` and `coverage2` : These two columns show the coverage near breakpoint1 and breakpoint2, respectively. The coverage is calculated as the number of fragments near the breakpoint on the side of the breakpoint that is retained in the fusion transcript. Note that the coverage calculation counts all fragments (even duplicates), whereas the columns `split_reads1`, `split_reads2`, and `discordant_mates` only count non-discarded reads. Fragments discarded due to being duplicates or other types of artifacts can be found in the column `filters`."

When I studied the results the coverage for gene1 is 10 and for gene2 6. I would have expected in the column `read_identifiers` that there would be 10 supporting reads. Instead, there were three supporting reads. Here is the example set (the first row is the example):
![Screenshot from 2024-10-01 17-04-04](https://github.com/user-attachments/assets/d16f0577-3085-4cf0-9578-060a1959529e)

Here are the reads supporting this fusion:
![Screenshot from 2024-10-01 17-04-28](https://github.com/user-attachments/assets/c7af263c-549e-4a26-937f-41c090fd6a71)

In case the text is too small to read, here it is in text:
<!DOCTYPE html>

<html>
<head>
	
	
		
</head>

<body>

#gene1 | gene2 | strand1(gene/fusion) | strand2(gene/fusion) | breakpoint1 | breakpoint2 | site1 | site2 | type | split_reads1 | split_reads2 | discordant_mates | coverage1 | coverage2 | confidence
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HNRNPA1L3 | HNRNPA1 | +/- | +/- | 16:51645954 | 12:54281506 | CDS | exon | translocation | 2 | 1 | 0 | 10 | 6 | medium

</body>

</html>

Here are the supporting reads:
<!DOCTYPE html>

<html>
<head>
	
	
</head>

<body>

read_identifiers
--
rb_E0.L.234582,rb_E0.L.191493,rb_E0.L.310699

</body>

</html>

Can you explain how to interpret this?  And if I am interested in getting the number of supporting reads of a fusion (from both output files of arriba) which column(s) should I used for it?

A note: this is arriba performed at a STARlong alignment.
 
Thanks in advance!

**Comment by suhrig** [comment]
I think you are confusing coverage and supporting reads. Coverage counts all reads near the breakpoint, regardless of whether they originate from the fusion or from the wild-type allele. The supporting reads (`split_reads1/2` and `discordant_mates`) count only the fusion reads. 

The purpose of the coverage columns is to help identify false positives. False-positive fusion calls often have hundreds to thousands of coverage reads, but only a handful of supporting reads. 

The column `read_identifiers` lists only the supporting reads. Since `split_reads1/2` + `discordant_mates` equals 3, you find three reads there.

>  And if I am interested in getting the number of supporting reads of a fusion (from both output files of arriba) which column(s) should I used for it?

`split_reads1/2` + `discordant_mates`. They are in both output files.

**Comment by YinYangKarly** [comment]
Thank you for your explanation!  So for the supporting reads I need to add the reads from `split_reads1/2` and `discordant_mates `together to get the total number?

**Comment by suhrig** [comment]
Almost. These columns only count the high-quality reads.

Sometimes, there are also numbers in the column `filters` (in parentheses). These are reads which were discarded by a filter. They are not counted in the split_reads/discordant_mates columns. To get the full count, you would need to parse this column, too. However, beware that this column also contains duplicate reads and multi-mapping reads, which one usually does not want to count.

**Comment by YinYangKarly** [comment]
Thank you! It is clear now!
