### ISSUE TITLE
About --transcriptSelection option

### ISSUE THREAD

**Issue by emiCbio** [suhrig/arriba#259]
Thank you for developing such a useful tool. 

I have a question about the following section of Arriba's command line options.
https://arriba.readthedocs.io/en/latest/command-line-options/#:~:text=%2D%2DtranscriptSelection%3Dcoverage%7Cprovided%7Ccanonical
At the end of the paragrah, it says that the default for --transcriptSelection is 'provided',
but earlier in the explanation, it seems to say that the default is 'coverage'.
Is my understanding correct that the default is 'provided'?

As far as I investigated, the following modification to the default parameter of "--transcriptSelection" is not reflected in the documentation.
https://github.com/suhrig/arriba/commit/92e09d05dbd693fe7bad2af27cf740229361c199

Thanks

**Comment by suhrig** [comment]
You're right. `provided` is the default. The documentation needs updating. Thanks for pointing out!

**Comment by emiCbio** [comment]
I got it. Thanks for your reply!

**Comment by suhrig** [comment]
Fixed in the `develop` branch now. Thanks again for reporting.
