### ISSUE TITLE
Understanding -S

### ISSUE THREAD

**Issue by cpsosa** [suhrig/arriba#263]
Hello,

According to the manual -S is:
min_support : This filter discards all events with fewer reads than specified by the parameter -S (default 2).

What reads does the code look at?  Or all of them, the runs that I have seen look like the filter is not obeyed but that could reflect that I do not fully understand -S or what reads does it check.

split_reads1    split_reads2    discordant_mates        coverage1           coverage2

Thanks,

**Comment by suhrig** [comment]
Hi, 

It removes all fusion candidates with less than 2 reads (split_reads1 + split_reads2 + discordant_mates). Only reads which have not been removed by preceeding filters are considered. In case of intragenic rearrangements, only split_reads1+2 are considered. Note that succeeding filters may recover some candidates discarded by this filter, so you may find a few fusions with less than 2 reads actually.

**Comment by cpsosa** [comment]
Thank you!  Very helpful.
