### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by li059059** [suhrig/arriba#3]
I git clone this software, but compile error (see below)  was got when i run make command in Centos 6.
How to fix this make error?

$make
make -C source arriba
make[1]: Entering directory `/share/Data01/liwujiao/biosoft/arriba/source'
g++ -c -pthread -std=c++0x -O2 -w -I. -I.. -I../samtools-1.3 -I../samtools-1.3/htslib-1.3 annotation.cpp -lz
g++ -c -pthread -std=c++0x -O2 -w -I. -I.. -I../samtools-1.3 -I../samtools-1.3/htslib-1.3 assembly.cpp -lz
g++ -c -pthread -std=c++0x -O2 -w -I. -I.. -I../samtools-1.3 -I../samtools-1.3/htslib-1.3 options_arriba.cpp -lz
options_arriba.cpp: In function 'void print_usage(const std::string&)':
options_arriba.cpp:141: error: call of overloaded 'to_string(float&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:144: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:147: error: call of overloaded 'to_string(float&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:150: error: call of overloaded 'to_string(float&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:152: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:159: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:162: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:167: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:169: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:172: error: call of overloaded 'to_string(float&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:175: error: call of overloaded 'to_string(float&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:180: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
options_arriba.cpp:185: error: call of overloaded 'to_string(unsigned int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
make[1]: *** [options_arriba.o] Error 1
make[1]: Leaving directory `/some/dir/arriba/source'
make: *** [arriba] Error 2

**Comment by suhrig** [comment]
Dear Li,

Thanks for bringing this to my attention. I have never tested Arriba with older compilers. Apparently, CentOS 6 has no overloaded function of to_string() for the float data type. In addition, there are a number of other compiler errors that come up. I will release a new version of Arriba after the holidays and make sure the code of this release is compatible with CentOS 6. Please check back in January.

P.S.: It is not recommended to use `git clone` to download Arriba. You should rather download the latest version of the software (currently v0.11.0) from the [releases page](https://github.com/suhrig/arriba/releases). The git repository does not include the blacklist. I will update the installation instructions to state this more clearly.

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Li,

Until I have adjusted the code for CentOS 6, you can install Arriba via Docker as outlined in the `README.md`.

Or - provided you have root privileges - you can install a newer compiler. There is a nice tutorial for CentOS 6 here:
https://edwards.sdsu.edu/research/c11-on-centos-6/
I could successfully compile Arriba on CentOS 6 following these instructions.

Regards,
Sebastian

**Comment by li059059** [comment]
Hi Sebastian,

Thanks for your help. I have downloaded the arriba_v0.11.0.tar.gz file. and unpack it. I found a executable  "arriba" file in it, arriba could be executed by export a higher version of  glibc in $LD_LIBRARY_PATH .

**Comment by suhrig** [comment]
The new release uses C++03-compatible code and compiles on CentOS 6 without errors. Moreover, the precompiled binaries also run on CentOS 6 without the need to point to a different glibc using $LD_LIBRARY_PATH. Feel free to give it a try.
