### ISSUE TITLE
All fusions going to "fusions.discarded.tsv"

### ISSUE THREAD

**Issue by CarmenBugarin** [suhrig/arriba#32]
Hi,

First of all, thanks for this amazing tool, it has been very useful to predict some of the protein fusions of my samples.

I have used arriba before with a different batch of samples without any issue. However, the last sequencing samples I tried to run with Arriba gave me some warning/errors and the "fusions.tsv" file is empty.

The output:

Loading annotation from '/mnt/lustre/users/k/RNAseq_RD/ReferenceGenome/Homo_sapiens.GRCh38.77.gtf.gz'
Loading assembly from '/mnt/lustre/users/k/RNAseq_RD/ReferenceGenome/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz'
Reading chimeric alignments from '/dev/stdin' (total=86)
Filtering multi-mappers and single mates (remaining=86)
Detecting strandedness (no)
Annotating alignments
Filtering duplicates (remaining=75)
Filtering mates which do not map to interesting contigs (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y) (remaining=74)
Estimating mate gap distributionWARNING: not enough chimeric reads to estimate mate gap distribution, using default values
Filtering read-through fragments with a distance <=10000bp (remaining=47)
Filtering inconsistently clipped mates (remaining=41)
Filtering breakpoints adjacent to homopolymers >=6nt (remaining=41)
Filtering fragments with small insert size (remaining=33)
Filtering alignments with long gaps (remaining=33)
Filtering fragments with both mates in the same gene (remaining=33)
Filtering fusions arising from hairpin structures (remaining=33)
Filtering reads with a mismatch p-value <=0.01 (remaining=31)
Filtering reads with low entropy (k-mer content >=60%) (remaining=29)
Finding fusions and counting supporting reads (total=27)
Merging adjacent fusion breakpoints (remaining=27)
Estimating expected number of fusions by random chance (e-value)
Filtering fusions with both breakpoints in adjacent non-coding/intergenic regions (remaining=27)
Filtering intragenic fusions with both breakpoints in exonic regions (remaining=27)
Filtering fusions with <2 supporting reads (remaining=5)
Filtering fusions with an e-value >=0.3 (remaining=5)
Filtering fusions with both breakpoints in intronic/intergenic regions (remaining=5)
Filtering PCR fusions between genes with an expression above the 99.8% quantile (remaining=5)
Searching for fusions with spliced split reads (remaining=5)
Selecting best breakpoints from genes with multiple breakpoints (remaining=3)
Searching for fusions with >=4 spliced events (remaining=3)
Filtering blacklisted fusions in '/users/k1470099/arriba_v1.1.0/database/blacklist_hg38_GRCh38_2018-11-04.tsv.gz' (remaining=1)
Filtering fusions with anchors <=23nt (remaining=1)
Filtering end-to-end fusions with low support (remaining=1)
Filtering fusions with no coverage around the breakpoints (remaining=1)
Indexing gene sequences
Filtering genes with >=30% identity (remaining=0)
Re-aligning chimeric reads to filter fusions with >=80% mis-mappers (remaining=0)
Selecting best breakpoints from genes with multiple breakpoints (remaining=0)
Searching for additional isoforms (remaining=0)
Assigning confidence scores to events
Writing fusions to file '/mnt/lustre/users/k/RNAseq_RD/output/fusions.tsv'
Writing discarded fusions to file '/mnt/lustre/users/k/RNAseq_RD/output/fusions.discarded.tsv'

Are there any parameters I should change? So far I have been using the default settings but as I said they work with previous samples.

The script I am running:
`#$ -S /bin/bash
#$ -o /mnt/lustre/users/k
#$ -e /mnt/lustre/users/k
#$ -l h_vmem=40G

module load bioinformatics/STAR/2.7.0f 

STAR --runThreadN 8 \
--runMode alignReads \
--genomeDir /mnt/lustre/users/k/RNAseq_RD/ReferenceGenome \
--readFilesIn /mnt/lustre/users/k/RNAseq_RD/R1_001_1.fastq.gz /mnt/lustre/users/k1470099/RNAseq_RD/R2_001_2.fastq.gz --readFilesCommand zcat \
--outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 \
--outFilterMultimapNmax 1 --outFilterMismatchNmax 3 \
--chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3  --winBinNbits 15 |
/users/k/arriba_v1.1.0/./arriba -x /dev/stdin \
-g /mnt/lustre/users/k/RNAseq_RD/ReferenceGenome/Homo_sapiens.GRCh38.77.gtf.gz -a /mnt/lustre/users/k/RNAseq_RD/ReferenceGenome/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz -b /users/k/arriba_v1.1.0/database/blacklist_hg38_GRCh38_2018-11-04.tsv.gz  \
-o /mnt/lustre/users/k/RNAseq_RD/output/tes_fusions.tsv -O /mnt/lustre/users/k/RNAseq_RD/output/tes_fusions.discarded.tsv `

Thanks in advance!

**Comment by suhrig** [comment]
Hi Carmen,

Glad to hear you find Arriba useful! The sample as a strikingly low number of chimeric reads (86). The number should be in the order of hundreds of thousands to millions. I'm suspecting a sample or alignment issue. What's the total number of reads and mapped reads? Can you paste/attach the STAR log file `Log.final.out`?

Regards,
Sebastian

**Comment by suhrig** [comment]
Hi Carmen, as part of my "issue killing spree" for the release of Arriba 2.0.0, I am closing this issue as well. Since I have not heard back in quite some while, I suspect the question is no longer relevant. I am happy to help out if you still have problems (whether it be this one or others). Best regards, Sebastian
