### ISSUE TITLE
file batch analysis

### ISSUE THREAD

**Issue by foxchase** [suhrig/arriba#35]
Dear arriba developers,
Is there an option to analyze multiple samples at a time? 

Thank you,

**Comment by suhrig** [comment]
Hi foxchase,

Do you mean multiple samples from the same tumor (or related tumors, such as primary and metastasis)? Arriba currently does not provide tools to integrate results from related samples. The simplest option is to pool the FastQ files and run Arriba as if it were a single sample. Alternatively, you can run Arriba on all samples individually and combine the fusion calls (union, intersection, found in X out of Y samples, ...). If you need help with this, let me know.

If you mean multiple unrelated samples, then you might want to check out a batch processing script developed by MattBashton: https://github.com/MattBashton/aloft

Regards,
Sebastian

**Comment by foxchase** [comment]
Thank you. Aloft is what i need.

On Dec 29, 2019 9:25 AM, suhrig <notifications@github.com> wrote:
EXTERNAL MESSAGE. DO NOT open attachments or click links from unknown senders or unknown emails.
________________________________


Hi foxchase,

Do you mean multiple samples from the same tumor (or related tumors, such as primary and metastasis)? Arriba currently does not provide tools to integrate results from related samples. The simplest option is to pool the FastQ files and run Arriba as if it were a single sample. Alternatively, you can run Arriba on all samples individually and combine the fusion calls (union, intersection, found in X out of Y samples, ...). If you need help with this, let me know.

If you mean multiple unrelated samples, then you might want to check out a batch processing script developed by MattBashton: https://github.com/MattBashton/aloft<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattBashton%2Faloft&data=02%7C01%7Cjianming.pei%40fccc.edu%7C03a3d43161aa43da01cc08d78c6b0092%7C6c85bf6157fb436280e22cd2d7bef6a0%7C0%7C0%7C637132263522858540&sdata=EITHXxb09r0gm55i4XFqXlYNR9JV1dZIJrWr8x1%2FSlY%3D&reserved=0>

Regards,
Sebastian

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuhrig%2Farriba%2Fissues%2F35%3Femail_source%3Dnotifications%26email_token%3DAG3M4DSHWZVIDG7WZRMU64DQ3CXO3A5CNFSM4KAVX6E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZATKY%23issuecomment-569510315&data=02%7C01%7Cjianming.pei%40fccc.edu%7C03a3d43161aa43da01cc08d78c6b0092%7C6c85bf6157fb436280e22cd2d7bef6a0%7C0%7C0%7C637132263522868532&sdata=MVf7CqRwW3qE8q5khss1PWkGZxD04dsIL84DGZzGMJI%3D&reserved=0>, or unsubscribe<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG3M4DXUNFTLEPGX73UKDEDQ3CXO3ANCNFSM4KAVX6EQ&data=02%7C01%7Cjianming.pei%40fccc.edu%7C03a3d43161aa43da01cc08d78c6b0092%7C6c85bf6157fb436280e22cd2d7bef6a0%7C0%7C0%7C637132263522868532&sdata=bxChLgHNwV67sPCUBXKR1I2z9zFNMjip3gYxyfTv1fc%3D&reserved=0>.


________________________________

This electronic message is intended to be for the use of the named recipient, and may contain information that is confidential or privileged. This communication may contain protected health information (PHI) that is legally protected from inappropriate disclosure by the Privacy Standards of the Health Insurance Portability and Accountability Act (HIPAA) and relevant Pennsylvania Laws. You can direct questions concerning PHI or HIPAA to the Corporate Compliance and Privacy Officer at (215) 707-5605. If you are not the intended recipient, please note that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this message in error, you should notify the sender immediately by telephone or by return e-mail and delete and destroy all copies of this message.
