### ISSUE TITLE
How to use GENCODE annotation with arriba?

### ISSUE THREAD

**Issue by maya123z** [suhrig/arriba#42]
I am attempting to use the hg38 annotation from GENCODE to run arriba. However it gave me "ERROR: failed to parse GTF file, please consider using -G". I added the following: "-G gene_name=gene_id gene_id=gene_id" but I got "ERROR: Malformed GTF features: gene_id=gene_id." This is where I got the annotation file from: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.annotation.gtf.gz

**Comment by suhrig** [comment]
Hi Maya,

GENCODE annotation should work right away. There should be no need to specify `-G`. I just tested the GTF file you linked using Arriba version 1.2.0 and it worked. I suspect you are falling victim to a trivial error (typo, wrong file, ...). Can you post your Arriba command and make sure your GTF file is not corrupt? The md5sum of the compressed GTF file should be `7def5e8043acc41182e10eb04f31f8f4`. The uncompressed file should give you `b4b6b98bc81eae6bb1ed27e2d41d6f8f`.

Regards,
Sebastian

**Comment by maya123z** [comment]
Hi Sebastian, you’re right! It was a pesky typo that I have now fixed. However it’s now giving me a different error. “ERROR: could not find sequence of contig '10’”. This is a human genome so I’m not sure why it’s not finding chromosome 10. I generated my reference genome with the following command:

STAR --runMode genomeGenerate --runThreadN 16 --genomeDir STARindex_hg38 --genomeFastaFiles hg38.fa

Fasta came from:  http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz

**Comment by suhrig** [comment]
Again, this has been tested successfully and should work. What platform are you using? Is it MacOS? Another user recently reported similar symptoms on a Mac (#37).

If you are not using a Mac, the issue must be something else. Can you post your Arriba command?

> Edit 2: Also I noticed that sometimes when I run arriba, it gives me the same "failed to parse GTF" error, but then if I run the exact command again a few minutes later it's fine.

That sounds odd. Are you using the precompiled binary or have you compiled yourself?

**Comment by maya123z** [comment]
I am on a Mac, and your solution to use the gzipped version solve the issue! Thanks for your prompt reply.
I installed arriba using conda.

**Comment by suhrig** [comment]
> I am on a Mac, and your solution to use the gzipped version solve the issue!

Thanks for the feedback. This is going to be fixed with the next release of Arriba and the workaround will not longer be necessary.

I didn't expect there to be so many Mac users. In fact, I never seriously considered supporting MacOS in the beginning. But given the demand, I should improve on that. Let me know, if you run into any additional weird issues. I have hardly tested Arriba on a Mac and would be interested in finding out about Mac-specific problems.

Regarding the intermittent `failed to parse GTF` errors, you might want to try [compiling from source](https://arriba.readthedocs.io/en/latest/quickstart/#manual-installation). It's hardly more complicated than installing via conda. You only need to make sure you have `xz`installed (`brew install xz`) and then run `make`.

**Comment by maya123z** [comment]
I didn't get the error using the gzipped GTF file, but the error only seems to occur occasionally. I'll try it a few more times at random intervals and see if it continues running without any errors.

**Comment by maya123z** [comment]
Hello again, I am having another issue with draw_fusions.R. It seems this script was not installed to my path. When I echo $PATH it's not in there. Perhaps another Mac-specific issue?

**Comment by suhrig** [comment]
How did you manage to install Arriba via conda in the first place? I never build a package for Mac and when I try to install it, conda throws a `PackagesNotFoundError` error.

`draw_fusions.R` should be in the same directory as the `arriba` binary. Type `which arriba` to locate it. Maybe the executable bit is missing. You can add it with `chmod a+x .../draw_fusions.R`.

I just installed R on a Mac and downloaded the `draw_fusions.R` script manually. It works on my system. That `unexpected end of input` error you're seeing looks like the file may be incomplete.

**Comment by maya123z** [comment]
I just used conda install -c bioconda arriba  which seemed to work fine. draw_fusions.R worked fine after I fixed a mistake in my manual download.

**Comment by suhrig** [comment]
Hi Maya,

[Arriba 2.0.0 is out](https://github.com/suhrig/arriba/releases/tag/v2.0.0). It officially supports MacOS and should no longer suffer from intermittent failures to read GTF files. So I'm closing this issue as resolved. Feel free to reopen if you still run into problems related to this.

Note that the bioconda package is not ready yet. I am still waiting for approval to be merged into the bioconda repository. This should only take a few days, though.

Regards,
Sebastian
