### ISSUE TITLE
Compatibility with STAR >2.7.2a

### ISSUE THREAD

**Issue by MattBashton** [suhrig/arriba#44]
Hi, do you know if Arriba will work as intended with versions of STAR greater than 2.7.2a. I note in the release notes that with reference to this STAR release that behaviour with respect to Chimeric reads changed:

> Chimeric read reporting now requires that the chimeric read alignment score higher than the alternative non-chimeric alignment to the reference genome. The Chimeric.out.junction file now includes the scores of the chimeric alignments and non-chimeric alternative alignments, in addition to the PEmerged bool attribute.

It's specifically the presence of scores for non-chimeric alternatives, I'm assuming this is a new feature of STAR?  I don't see anything in the release notes for Arriba 1.2.0 about the changes in STAR and I'm cautious that alternations to Chimeric.out.junction format might result in unwanted behaviour or non-chimeric alternatives being parsed.

**Comment by suhrig** [comment]
Hi Matt,

Arriba does not make use of STAR's proprietary output format `Chimeric.out.junction`. It only uses the alignment files (`Chimeric.out.sam` and/or `Aligned.out.bam`). As such, the changes introduced in version 2.7.2 do not affect Arriba at all. In fact, I have tested it successfully with version 2.7.3.

Regards,
Sebastian

**Comment by MattBashton** [comment]
Hey thanks this is good to know, I had been holding off upgrading my STAR binary because of this.

**Comment by suhrig** [comment]
Hi Matt, I'm closing this issue. If you upgrade to Arriba 2.0.0 - [released just now](https://github.com/suhrig/arriba/releases/tag/v2.0.0) - you are actually encouraged to upgrade STAR to the latest version (2.7.6a) to make use of multi-mapping chimeric reads.
