### ISSUE TITLE
Known fusion format

### ISSUE THREAD

**Issue by ycl6** [suhrig/arriba#49]
Hi,

I am wondering what is the expected file format for `-k known_fusions.tsv`

I recently downloaded the know fusions from COSMIC Complete Fusion Export as recommanded in the Arriba guide. However, the `CosmicFusionExport.tsv.gz` file has the following format, which I think is not what's expected by Arriba
```
Sample ID	Sample name	Primary site	Site subtype 1	Site subtype 2	Site subtype 3	Primary histology	Histology subtype 1	Histology subtype 2	Histology subtype 3	Fusion ID	Translocation Name	5' Chromosome	5' Genome start from	5' Genome start to	5' Genome stop from	5' Genome stop to	5' Strand	3' Chromosome	3' Genome start from	3' Genome start to	3' Genome stop from	3' Genome stop to	3' Strand	Fusion type	Pubmed_PMID
749711	HCC1187	breast	NS	NS	NS	carcinoma	ductal_carcinoma	NS	NS	665	ENST00000360863.10(RGS22):r.1_3555_ENST00000369518.1(SYCP1):r.2100_3452	8	99981937	99981937	100106116	100106116	-	1	114944339	114944339	114995367	114995367	+	Inferred Breakpoint	20033038
749711	HCC1187	breast	NS	NS	NS	carcinoma	ductal_carcinoma	NS	NS	665	ENST00000360863.10(RGS22):r.1_3555_ENST00000369518.1(SYCP1):r.2100_3452	8	99981937	99981937	100106116	100106116	-	1	114944339	114944339	114995367	114995367	+	Observed mRNA	20033038
749711	HCC1187	breast	NS	NS	NS	carcinoma	ductal_carcinoma	NS	NS	689	ENST00000324093.8(PLXND1):r.1_2864_ENST00000393238.7(TMCC1):r.918_5992	3	129574336	129574336	129606818	129606818	-	3	129647792	129647792	129671264	129671264	-	Inferred Breakpoint	20033038
749711	HCC1187	breast	NS	NS	NS	carcinoma	ductal_carcinoma	NS	NS	689	ENST00000324093.8(PLXND1):r.1_2864_ENST00000393238.7(TMCC1):r.918_5992	3	129574336	129574336	129606818	129606818	-	3	129647792	129647792	129671264	129671264	-	Observed mRNA	20033038
749711	HCC1187	breast	NS	NS	NS	carcinoma	ductal_carcinoma	NS	NS	695	ENST00000285518.10(AGPAT5):r.1_898_ENST00000344683.9(MCPH1):r.2529_8039	8	6708357	6708357	6741751	6741751	+	8	6642994	6642994	6648504	6648504	+	Inferred Breakpoint	20033038
```

**Comment by suhrig** [comment]
Hi I-Hsuan,

The accepted format is very simple: It's a tab-separated file with just two columns, where each line specifies a pair of genes by name, e.g., 

```
TMPRSS2	ERG
BCR	ABL1
```
The order of the genes does not matter - Arriba checks both orders.

Sorry if the link to the COSMIC page confused you. The COSMIC format is not the accepted input format, it is just a good source from where to get a comprehensive list of known fusions. Ideally, I would like to distribute a readily usable list with Arriba, but the license agreement of COSMIC prohibits redistribution.

Regards,
Sebastian

**Comment by ycl6** [comment]
Thanks @suhrig 
I'll generate the file as you suggested.

**Comment by ahwanpandey** [comment]
@suhrig you mention that the order of the genes doesn't matter in the known fusions file. However, the docs for 2.4.0 mentions that it is important.

![image](https://github.com/suhrig/arriba/assets/8450532/34cbc3b3-15e6-4c49-8ff9-222e062473c2)

Also, can I write both the gene symbols as well as the coordinates in the known fusions file? Eg.. the following fusion is between exon1 of SLC25A40 to exon2 of ABCB1. Or is it redundant?

#SLC25A40    ABCB1

![image](https://github.com/suhrig/arriba/assets/8450532/46370b8b-0901-4469-9a40-41514de58e72)

**Comment by suhrig** [comment]
The order of the genes didn't matter at the time that I wrote this statement. Now it does.

It is not redundant to list fusions by gene names and breakpoints. Arriba applies the most sensitive filters to fusions specified by breakpoint coordinates - even more sensitive than fusions specified by gene names.

**Comment by ahwanpandey** [comment]
@suhrig quick question. My BAM files and GTFs have "chr1", "chr2" etc.. contig naming but the known fusion supplied by Arriba has "1", "2" etc.. Do I need to update the known fusion file with the "chr" prefix or it doesn't matter? Thanks.

**Comment by suhrig** [comment]
This does not matter. Arriba harmonizes the chr prefixes when it loads the files.
