### ISSUE TITLE
add @PG line to bam output from extract_read-through_fusions?

### ISSUE THREAD

**Issue by plijnzaad** [suhrig/arriba#5]
Hi, 

thanks for the nice code and extensive documentation. Would it be possible for you to make `extract_read-through_fusions` output an extra `@PG` line into the resulting bam file? Thanks a lot!

**Comment by suhrig** [comment]
Good suggestion. I'm putting it on my todo list for the next release. Will keep you updated.

**Comment by suhrig** [comment]
Hi plijnzaad,

A new release of Arriba is available. The [workflow is now simpler (and faster)](https://arriba.readthedocs.io/en/v1.0.0/workflow/). `extract_read-through_fusions` is obsolete and no `read_through_fusions.bam` file is generated anymore. Therefore, there is no need to add a `@PG` header anymore.

Regards,
Sebastian
