### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by asaki1986** [suhrig/arriba#54]
Hi,

I git clone the repo, but got the following error while compiling arriba under Centos 7.

/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:257: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:258: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:260: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:263: undefined reference to `curl_easy_perform'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:277: undefined reference to `curl_slist_free_all'
htslib/libhts.a(hfile_s3_write.o): In function `s3_write':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:455: undefined reference to `curl_easy_getinfo'
htslib/libhts.a(hfile_s3_write.o): In function `s3_write_open':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:681: undefined reference to `curl_easy_init'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:726: undefined reference to `curl_easy_getinfo'
htslib/libhts.a(hfile_s3_write.o): In function `complete_upload':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:321: undefined reference to `curl_easy_reset'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:322: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:323: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:324: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:325: undefined reference to `curl_easy_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:326: undefined reference to `curl_easy_setopt'
htslib/libhts.a(hfile_s3_write.o):/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:327: more undefined references to `curl_easy_setopt' follow
htslib/libhts.a(hfile_s3_write.o): In function `complete_upload':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:333: undefined reference to `curl_easy_perform'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:347: undefined reference to `curl_slist_free_all'
htslib/libhts.a(hfile_s3_write.o): In function `s3_close':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:506: undefined reference to `curl_easy_getinfo'
htslib/libhts.a(hfile_s3_write.o): In function `hfile_plugin_init_s3_write':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:859: undefined reference to `curl_global_init'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:866: undefined reference to `curl_share_init'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:874: undefined reference to `curl_share_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:875: undefined reference to `curl_share_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:876: undefined reference to `curl_share_setopt'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:885: undefined reference to `curl_version_info'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:879: undefined reference to `curl_share_cleanup'
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:880: undefined reference to `curl_global_cleanup'
htslib/libhts.a(hfile_s3_write.o): In function `s3_write_exit':
/home/jjiang/work/fusion/arriba/htslib/hfile_s3_write.c:831: undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'arriba' failed
make: *** [arriba] Error 1

curl, libcurl have been already installed with yum.

Any method to fix this?

**Comment by suhrig** [comment]
In addition to `curl` and `libcurl`, you probably also need to install `libcurl-devel`.

Some additional remarks:

1. You should not use `git clone` to download Arriba. The git repository does not include the blacklist, which is highly recommended to use. Instead, you should download Arriba from the [releases page](https://github.com/suhrig/arriba/releases).

2. In contrast to the git repository, the releases tarballs also come bundled with a precompiled `arriba` binary, which you can use right away. In most situations there is no need to compile from scratch.

3. It seems you are using htslib-1.10. Arriba has only been tested with htslib-1.9. Although I assume that it works just as fine with htslib-1.10, it is not officially supported yet and you might encounter unexpected behavior. The download files on the releases page are bundled with the recommended htslib version to use.

4. For a smooth installation experience, please stick to the [quickstart guide in the user manual](https://arriba.readthedocs.io/en/latest/quickstart/).

**Comment by asaki1986** [comment]
> In addition to `curl` and `libcurl`, you probably also need to install `libcurl-devel`.
> 
> Some additional remarks:
> 
> 1. You should not use `git clone` to download Arriba. The git repository does not include the blacklist, which is highly recommended to use. Instead, you should download Arriba from the [releases page](https://github.com/suhrig/arriba/releases).
> 2. In contrast to the git repository, the releases tarballs also come bundled with a precompiled `arriba` binary, which you can use right away. In most situations there is no need to compile from scratch.
> 3. It seems you are using htslib-1.10. Arriba has only been tested with htslib-1.9. Although I assume that it works just as fine with htslib-1.10, it is not officially supported yet and you might encounter unexpected behavior. The download files on the releases page are bundled with the recommended htslib version to use.
> 4. For a smooth installation experience, please stick to the [quickstart guide in the user manual](https://arriba.readthedocs.io/en/latest/quickstart/).

Hi suhrig,

Thanks for reply.
Package libcurl-devel-7.29.0-54.el7_7.2.x86_64 already installed and latest version.

1. I did use git clone to download the repo.
2. I tried to download arriba binary from release page, however, the download speed is quite slow. I am still trying.
3. I switched htslib-1.10 to 1.9, but not changed.

Thanks

**Comment by suhrig** [comment]
> 2. I tried to download arriba binary from release page, however, the download speed is quite slow. I am still trying.

That's odd. The file is not particularly big and takes only a few minutes with my Internet connection.

> 3. I switched htslib-1.10 to 1.9, but not changed.

Is the error exactly the same? That can't be, because 1.9 does not even have the file that throws the error (`hfile_s3_write.c`). Can you double-check that it really uses 1.9?

**Comment by asaki1986** [comment]
> > 1. I tried to download arriba binary from release page, however, the download speed is quite slow. I am still trying.
> 
> That's odd. The file is not particularly big and takes only a few minutes with my Internet connection.
> 
> > 1. I switched htslib-1.10 to 1.9, but not changed.
> 
> Is the error exactly the same? That can't be, because 1.9 does not even have the file that throws the error (`hfile_s3_write.c`). Can you double-check that it really uses 1.9?

Success with v1.8 htslib. Thanks.
