### ISSUE TITLE
tool logo?

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#55]
https://cdn-static.denofgeek.com/sites/denofgeek/files/2016/04/speedy-gonzales.jpg

I think its a match! :)

**Comment by suhrig** [comment]
I can't open the link (404 file not found), but yeah, that's indeed where the name comes from: Arriba is the Speedy Gonzales of fusion detection tools. There is never going to be a Speedy Gonzales-related logo, though, because that would infringe on Warner Bros' copyright.

**Comment by erprateek** [comment]
sure thats understandable. Ill put up an image for folks to have a reference to what I meant :) 
![610nIQKHcQL _AC_SL1444_](https://user-images.githubusercontent.com/2459065/80450131-b12ab880-88d5-11ea-978e-dee60f6516a0.jpg)

**Comment by suhrig** [comment]
I once used this for a poster at an internal conference: https://imgur.com/a/8N0GElP :-D
But as I said, I cannot make this the official logo due to copyright restrictions.
