### ISSUE TITLE
How to cite Arriba?

### ISSUE THREAD

**Issue by plijnzaad** [suhrig/arriba#6]
Hi, 

what would be the best way to cite Arriba? A biorXiv preprint would be excellent! Thanks,

Philip

**Comment by suhrig** [comment]
Dear Philip,

I'm still working on a method paper about Arriba. Until then, please refer to Arriba in your methods section as follows (or similar):

> We used Arriba (https://github.com/suhrig/arriba/) to detect gene fusions from RNA-Seq data.

Regards,
Sebastian

**Comment by heweihuang** [comment]
NAs introduced by coercion

**Comment by suhrig** [comment]
Hi Philip,

You may not remember opening this issue. But I surely have not forgotten. It finally happened. From now on, you can cite [our publication](https://doi.org/10.1101/gr.257246.119). I will update the README and user manual shortly. What a pleasure to finally close this issue ...

Regards,
Sebastian

**Comment by roryk** [comment]
Congrats Sebastian!

**Comment by DarioS** [comment]
> We compared the performance of Arriba v1.0.0 against six commonly used fusion detection algorithms ...

But, what about version 2.0.0? It must be even more accurate than the competitors. Also, would like to see evaluation for total RNA.

**Comment by plijnzaad** [comment]
congrats on the paper!

**Comment by suhrig** [comment]
> But, what about version 2.0.0?

Haha, you are absolutely right. The review took so long (a lot due to Corona lockdown) that it is almost time for a follow-up publication. It took a whopping 1.5 years from finishing the manuscript to publication ...

> Also, would like to see evaluation for total RNA.

Good point. I would be interested as well. I'm sure among the thousands of samples that I have run Arriba on, there are some total RNA ones. I just never looked at them specifically.

**Comment by roryk** [comment]
Hi Sebastian,

Can you add the paper at the bottom of your README.md and/or somewhere on the RTD cite? To find it I had to go in here. Do you have a Twitter account or anything I can RT an announcement about it?

**Comment by DarioS** [comment]
Perhaps it will be added once there is volume, issue and page numbers available. Currently, it's Advance Online Article.

Total RNA has many more false positives with the intronic, untailed, anti-sense Alu repeats, as shown in #92 which are discarded by sample preparation protocols that retain only poly-A tails. I can send adapter-trimmed FASTQs for algorithm testing, if needed.

**Comment by suhrig** [comment]
I am currently finalizing version 2.1.0. I will update the README / manual when I push the new release.

@DarioS: Thanks for the offer of sending FastQs. I might come back to you offer. I think I even have some samples with multiple libraries (polyA & total) such that I could make direct comparisons. Anyhow, we should continue the discussion in the appropriate issue (#92).
