### ISSUE TITLE
Documentation Clarifications

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#60]
I notice the resultant PDF that there is always either "reading frame unclear" or "No protein domains retained in fusion". Could the user guide discuss what this suggests? Could it have something to do with using a reference genome with chromosome names such as chr1, chr2 rather than 1, 2?

Another minor documentation issue:

```
[2020-05-01T16:45:56] Writing fusions to file '/tmp/fusionsTest.csv'
```

However, `head /tmp/fusionsTest.csv` shows that it's actually tab-separated - not comma-separated. The `draw_analysis.R` documentation correctly refers to TSV; `--fusions=fusions.tsv`.

**Comment by suhrig** [comment]
> is always either "reading frame unclear" or "No protein domains retained in fusion"

`reading frame unclear` means that Arriba was unable to determine the reading frame, i.e., the column `reading_frame` contains a dot. `No protein domains retained in fusion` means the fusion involves non-coding genes or UTRs only.

> Could it have something to do with using a reference genome with chromosome names such as chr1, chr2 rather than 1, 2?

No. Neither `arriba` nor `draw_fusions.R` care about the `chr` prefix.

> `[2020-05-01T16:45:56] Writing fusions to file '/tmp/fusionsTest.csv'`

This is not from the Arriba documentation, is it? As far as I can see, the documentation never mentions CSV files, it only ever talks about TSV files. Arriba does not care what you name your output files. I always generates TSV files.

**Comment by DarioS** [comment]
Oops. I specified `-o /tmp/fusionsTest.csv` subconsciously by mistake.
