### ISSUE TITLE
more than 2 genes in gene1 or gene2 column

### ISSUE THREAD

**Issue by yeswzc** [suhrig/arriba#61]
Hi,
Do anyone know if this is expected that a column (the first 2 columns) may have 2 genes separated my coma? For example:

> #gene1  gene2   strand1(gene/fusion)    strand2(gene/fusion)    breakpoint1     breakpoint2 ...
>CAPZA3(297913),RPL7P6(52051)    PLEKHA5 ./+     +/+     12:19037100     12:19132393 ...

Do this means fusion was detection between CAPZA3 and PLEKHA5, and between RPL7P6 and PLEKHA5? If so, why only one breakpoint was shown in breakpoint1 ?

Thank you!

**Comment by suhrig** [comment]
Hi Zhichao,

No, this does not mean that there are two fusions (CAPZA3--PLEKHA5 and RPL7P6--PLEKHA5). What it means is that the breakpoint given in the column `breakpoint1` is *between* the genes CAPZA3 and RPL7P6. The numbers given in parentheses (297913 and 52051) specify the distance to these genes.

You can find the documentation of the output file format here: https://arriba.readthedocs.io/en/latest/output-files/

Regards,
Sebastian

**Comment by yeswzc** [comment]
I see.
Thank you!
