### ISSUE TITLE
Whether Arriba supports the detection of multiple fusion of a breakpoint？

### ISSUE THREAD

**Issue by wuyingkongsuifeng74** [suhrig/arriba#63]
Dear professor：
Whether Arriba supports the detection of multiple fusion of a breakpoint？For example, can two fusion events in the same gene of ALK  be detected by Arriba or not? 
EML4-ALK Fusion  2:42522656  **2:29446394**
NPM1-ALK Fusion   5:170818803  **2:29446394**

**Comment by suhrig** [comment]
Yes, it absolutely can. Two independent driver fusions in the same tumor is a rare occurrence, but I have seen such cases and Arriba detected them.

**Comment by wuyingkongsuifeng74** [comment]
Thank you for kind reply.
I met a problem，one of the fusion in the reference standard(ALK-NMP1) cannot be detected by Arriba.
I saw the reads around the breakpoint by IGV ,  the left part is the softclip reads of ALK, which can be mapped to the EML4 and NMP1 gene (Fig1),respectively, The latter can also be compared to other genes at the same time (Fig2). 
The right partner is the softclip reads of NMP1, on the  contrary,which  can't mapped the ALK gene. Do you have any good advice to deal with this case?




------------------------------------------------------------------
发件人：suhrig <notifications@github.com>
发送时间：2020年5月27日(星期三) 18:48
收件人：suhrig/arriba <arriba@noreply.github.com>
抄　送：吴玲清 <wulq@geneplus.org.cn>; Author <author@noreply.github.com>
主　题：Re: [suhrig/arriba] Whether Arriba supports the detection of multiple fusion of a breakpoint？ (#63)

Yes, it absolutely can. Two independent driver fusions in the same tumor is a rare occurrence, but I have seen such cases and Arriba detected them.

**Comment by suhrig** [comment]
> one of the fusion in the reference standard

What reference standard?

> Fig1

Did you send figures with your message? If so, they did not get through to me. I guess you have to use the GitHub webinterface, if you want to send images.

> The latter can also be compared to other genes at the same time

What exactly do you mean by "compared to other genes"? Do you mean mapped?

**Comment by wuyingkongsuifeng74** [comment]
The standard is a mixture of different cell lines with known fusion genes，ALK-NMP1 is one of the known fusion in it, with breakpoint is  NMP1(chr5:170818803)  ALK(chr2:29446394) respectively. which can not be detected by Arriba.
The Fig  is the demonstrate the detail of these fusion.  
![Uploading ALK-NPM1.png…]()

**Comment by suhrig** [comment]
> The standard is a mixture of different cell lines with known fusion genes

Do you mean the Universal Human Reference RNA? I am not aware of such a standard. I'd be grateful, if you point me to it, because this could be useful for benchmarking.

> The Fig is the demonstrate the detail of these fusion.

Unfortunately, the figure did not upload. It's a link to this thread instead of a link to a picture. Can you kindly try again?
