### ISSUE TITLE
download_references.sh fails inside docker

### ISSUE THREAD

**Issue by drtconway** [suhrig/arriba#65]
Hi Arriba,

I just pulled the biocontainers image (quay.io/biocontainers/arriba:1.2.0--h248197f_1), and ran download_references.sh.

It fails at line 104, because the grep implementation in the image does not support `-P`.

This might be considered a packaging bug in the biocontainer, since it uses the BusyBox image, not a "full" Ubuntu image, I guess.

**Comment by drtconway** [comment]
Oh. I see you have your own image.

**Comment by suhrig** [comment]
Thanks for the hint, nonetheless! I think, the `-P` is not even necessary, so I will remove it in future releases.
