### ISSUE TITLE
All relevant transcripts for each fusion event

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#66]
Hi Sebastian,

I wonder if it is possible to report out via Arriba, all the relevant transcripts for a given fusion event. My evaluation vs other fusion callers like FusionCatcher needs to report out what happened to the other transcripts in Arriba. Whether they are 'recognized' by Arriba or are they not expressed enough. 

Any help here would be appreciated!

**Comment by suhrig** [comment]
Hi Prateek,

Arriba uses the transcripts only for peptide sequence prediction. The expression of transcripts does not influence fusion calling. All that matters is the expression of at the fusion breakpoints. What exactly do you mean by "recognized"? Does Arriba miss fusions that FusionCatcher detects?

Regards,
Sebastian

**Comment by erprateek** [comment]
Well technically I havent found any such cases but there are certain transcripts that are a part of FusionCatcher results for the same given fusions are not for Arriba. I understand that it might be due to the annotation differences how FusioncCatcher uses hg38 ensembl vs Arriba GENCODE19 but I want to make sure I am not missing anything obvious.

**Comment by erprateek** [comment]
I was indeed referring to the transcript id column. I was trying to look for things where they are simple and not where they are complicated i.e. looking in Arriba rather than FC. So I finally understand what has been bothering me with the difference between the two tools that I have been trying to evaluate. 

With FusionCatcher, the predicted fused transcripts and predicted fused proteins are derived from the reference and not the evidence in the sample. However with Arriba, you look at the sample level evidence to make those calls. This leads to uncertain calls('?') in the protein sequence column in Arriba where is FusionCatcher comes out clean. This is understandable and the best explanation i have found so far.

**Comment by suhrig** [comment]
>  This leads to uncertain calls('?') in the protein sequence column in Arriba where is FusionCatcher comes out clean.
If that is what your question was aiming at, then yes, I can confirm that it is caused by Arriba using the sample whereas FusionCatcher using the reference.

**Comment by erprateek** [comment]
Yes sorry this was kind of hard for me to formulate. Arriba is selective towards the highly expressed transcript relevant for the sample. While FusionCatcher just dumps every transcript that intersects with the breakpoint. I will close this ticket.

**Comment by suhrig** [comment]
I find Arriba's approach to be more informative, because if all potentially relevant transcripts are dumped, then it's up to the user to figure out what the coding effect is, whereas Arriba tells you specifically what the coding effect is.
