### ISSUE TITLE
Question about GTF parsing 

### ISSUE THREAD

**Issue by cyruinous** [suhrig/arriba#69]
Hi Sebastian,

I have a question about GTF parsing arriba.
From what I understand through [arriba/source/annotation.cpp], when parsing the line of the GTF file at line 196, it seems that parsing is not possible when a space is entered in the second column (source).

[Curated Genomic] is entered in the source column of RefSeq GTF, so [WARNING: failed to parse line in GTF file] appears in the log file.

We also confirmed that no warning occurs when arriba is performed by replacing [Curated Genomic] with [CuratedGenomic].

Will this part be corrected?

**Comment by suhrig** [comment]
Yes, this will be corrected. In fact, it has already been fixed in the current development version of Arriba. As such, the fix will be part of the next release. Thanks for the suggestion nonetheless. It is always helpful to hear about the problems that users run into.
