### ISSUE TITLE
Separating genome downloading and indexing into two steps

### ISSUE THREAD

**Issue by dstueckm** [suhrig/arriba#72]
Hi there,

I'm attempting to download and index a reference genome as outlined in your quickstart guide, using the argument GRCh38+RefSeq for the ./download_references.sh script.
When allocating 8GB of RAM, the assembly and annotation files successfully download, but the program crashes with a "bad_alloc" memory error (as expected, as you mentioned you require 30+ GB). My issue is that on my HPC I can't access that much memory without sacrificing an internet connection, meaning I won't be able to download the files in the first place.
I was wondering if there is any way to modify this script to utilize the already downloaded files offline rather than attempting to re-download these files each time?

Thanks in advance!

**Comment by suhrig** [comment]
Yes, if you remove lines 48 to 108, then the script looks for existing files and won't attempt download them anew.

I have thought about splitting these two steps myself, but opted against doing so for two reasons:

1. I want to keep the download procedure as simple as possible. Splitting it up would mean that users would have to run two scripts. As usual, simplicity comes at the expense of flexibility, so users with special requests as in your case run into problems. I have also thought about enhancing the script in a way that it only downloads files if they are not already present. But then it would have to check the integrity of the files and there would have to be an option to skip the index generation step. Overall, this would make the script much more complicated than it has to be.

2. You are not obliged to use the script to download the reference files and generate the index. The script is only provided for convenience. Arriba also works with a user-generated index. You are free to download whatever assembly and annotation you favor (as long as the coordinates are compatible with hg19 or hg38). Note: If you use RefSeq, you need to convert the annotation to GTF, but you would have to do this anyway to generate the STAR index. So again, the script is merely for your convenience.

**Comment by dstueckm** [comment]
Thanks for the quick response, that works perfectly!
I do understand the logic for keeping it all together, and I appreciate the addition of this script as it does make things more foolproof.
