### ISSUE TITLE
breakpoint confirmation when both split reads1  and split reads2 were zero 

### ISSUE THREAD

**Issue by ahy1221** [suhrig/arriba#82]
Dear Suhrig,

Several fusions detected by arriba 1.2.0 reported zero split reads (both split reads1 and split reads2). 
I was wondering how does arriba confirm the breakpoint of these fusions when only discordant_mates were detected ?

Thank you for your explanation in advance!

Best,
Yao He

**Comment by suhrig** [comment]
Hi Yao He,

When a fusion prediction is made solely on the basis of discordant mates, the precise breakpoints cannot be determined. In such a case, Arriba reports the mapping coordinates of the discordant mates as breakpoints. The true breakpoints are most often within a distance of the average fragment size.

Does this answer your question?

Regards,
Sebastian

**Comment by ahy1221** [comment]
Thank you very much !  Very helpful !
