### ISSUE TITLE
fusions detected both in tumor and normal tissue, on the same gene at the same breakpoints

### ISSUE THREAD

**Issue by MariusGheorghe** [suhrig/arriba#86]
Hi Sebastian,

How's it going? All good I hope. 

I was playing with Arriba on some samples for which we have tumor **and** normal DNA. Part of the question I was trying to answer myself was: how many of the gene fusions detected in tumorous tissue are actually present in the normal tissue? But I found some weird behavior which I do not know if it reflect reality/biology or it's an artifact of the tool. Before going through the attached table with preliminary results, please keep in mind that the normal DNA comes from blood and the tumorous tissue from various types of cancer. 

What I've did to generate the table below was to collect all gene fusions (that were **not** discarded) from four samples, both detected in normal DNA and in tumor DNA, and merge them per sample between the tumor and normal, based on multiple columns: `gene1`, `gene2`, `breakpoint1`, `breakpoint2`, `strand1(gene/fusion)`, `strand2(gene/fusion)`. So, a pretty stringent merging criteria. This is what I got: [common_gene_fusions_per_sample.xlsx](https://github.com/suhrig/arriba/files/5480324/common_gene_fusions_per_sample.xlsx). Sorry if the formatting went bananas, but apparently `.tsv` is not supported and I don't really use Excel.

I left the breakpoints where the fusion was detected in case that info helps you, but I removed the strands (so let me know if you need that info also). As you can see, those common gene fusions occur on the same gene **and** exactly at the same breakpoint **and** on the same strand (gene/fusion) in both tumor and normal. The confidence score is mainly the same across these common gene fusions (albeit only for one it is `high`). 

I could not provide you with the fusion nucleotide sequence nor the predicted peptide sequence due to data sensitivity, but I've calculated a similarity score between the strings of the two fusion transcripts (tumor vs. normal) and the two predicted peptide sequences (tumor vs. normal). This score ranges from 0 (completely different) to 1 (identical strings) and it is based on string distances. As you can see, the resulting transcripts and peptides are highly similar.

Now, I do not know if this is actually going on biologically (again, normal tissue is from blood and tumorous tissue is from different types of cancer), or it is some systematic artifact or what it is. Do you have some insight as of the biological interpretation and/or computational interpretation? Thanks a lot in advance and let me know if you need more info.
Have a good day!

Marius

**Comment by suhrig** [comment]
I'm closing this issue, because GitHub created it twice.
