### ISSUE TITLE
Fusion Transcript Width and Exon Label Readability

### ISSUE THREAD

**Issue by DarioS** [suhrig/arriba#94]
Could the fusion plotting automatically make the transcript wider, so that the exon labels become readable, if it is a short one?

![image](https://user-images.githubusercontent.com/631218/102853943-80efe580-4475-11eb-9b57-42eb51baf497.png)

**Comment by suhrig** [comment]
Sorry, this is not possible, because then the fusion transcript would have a different scale than the originating transcripts. In all publication figures that I have seen, the fusion transcript and the originating transcripts have the same scale. So this convention should not be violated.
