### ISSUE TITLE
Incompatible STAR parameters

### ISSUE THREAD

**Issue by schmittel** [suhrig/arriba#96]
Hi there, 

I'm getting an error because of incompatible STAR parameters yet I'm trying to run it with the recommended settings for Arriba. Based on the Arriba documentation, I'm running STAR 2.7.7a with `--chimOutType WithinBAM HardClip` and `--chimMultimapNmax 50` but STAR throws the error:

```
EXITING because of fatal PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions
SOLUTION: re-run with --chimOutType Junctions
```

I get the same error when I run `--chimOutType SeparateSAMold`.

As far as I can tell, the `Chimeric.out.junction` file produced by `--chimOutType Junctions` is not supported by Arriba, so I was wondering what the recommended approach would be here?

Many thanks

**Comment by schmittel** [comment]
Nevermind... I was in the wrong Conda environment with an older version of STAR. Stupid mistake.

**Comment by suhrig** [comment]
I was just about to ask you to double-check. Glad you figured it out so quickly yourself. Sometimes little things like these can keep you busy for much longer than they should. Feel free to reach out again if you run into more complicated issues.
